#' Wrapper function to create an RTMB_Model instance
#'
#' @param data A list of data used for modeling.
#' @param parameters A list (or alist) of parameters.
#' @param log_prob A function or code generated by model_code().
#' @param transformed An optional function OR a list of expressions.
#' @param generate An optional function for generated quantities.
#' @param par_names A list of parameter names
#' @export
rtmb_model <- function(data, parameters, model,
                       transformed = NULL,
                       generate = NULL,
                       par_names = list()) {

  # 1. parameters への名前の注入
  build_par_list <- function(dat, params) {
    eval_env <- list2env(dat, parent = parent.frame())
    lapply(names(params), function(n) {
      p <- params[[n]]
      if (typeof(p) %in% c("language", "symbol")) {
        eval(p, envir = eval_env)
      } else {
        p
      }
    }) |> setNames(names(params))
  }
  evaluated_par_list <- build_par_list(data, parameters)

  # 2. 実行前のデータ・型チェック
  validate_data(data, evaluated_par_list)

  # 3. transformed と generate の評価
  raw_transformed <- substitute(transformed)
  if (!is.null(raw_transformed) && !is.function(transformed)) {
    transformed <- eval(bquote(transformed_code(.(raw_transformed), env = parent.frame())))
  }

  raw_generate <- substitute(generate)
  if (!is.null(raw_generate) && !is.function(generate)) {
    generate <- eval(bquote(transformed_code(.(raw_generate), env = parent.frame())))
  }

  # 4. モデルの構築とエラーハンドリング
  tryCatch({
    model_instance <- RTMB_Model$new(
      data         = data,
      par_list     = evaluated_par_list,
      log_prob     = model,
      transform    = transformed,
      generate     = generate,
      par_names    = par_names
    )
    return(model_instance)

  }, error = function(e) {
    err_msg <- conditionMessage(e)

    # ADクラス消失・非数値エラーの翻訳 (日本語・英語両対応)
    if (grepl("lost class attribute", err_msg) ||
        grepl("Invalid argument to 'advector'", err_msg) ||
        grepl("数学関数に非数値引数", err_msg) ||
        grepl("non-numeric argument to mathematical function", err_msg)) {
      stop(
        "【モデル構築エラー】自動微分(AD)の型が途中で消失したか、非数値が渡されました。\n",
        "・原因: model_code 内で AD対応していない関数（自作の関数や一部のbase関数など）を通したか、\n",
        "        空の array() に対して for ループで逐次代入を行って型が壊れた可能性があります。\n",
        "・対策: 計算を model_code 内で直接記述するか、行列のベクトル化計算を使用してください。\n",
        "[元のエラー]: ", err_msg,
        call. = FALSE
      )
    }

    # 不正な演算エラーの翻訳 (C++由来のエラーは基本的に英語のまま出ます)
    if (grepl("illegal operation", err_msg) || grepl("not a valid 'advector'", err_msg)) {
      stop(
        "【モデル構築エラー】実行不可能な演算、または型の不整合が発生しました。\n",
        "・原因: 行列の掛け算(%*%)の左右で次元が合っていない、または Dim() の型指定 (CF_cov, lower_tri など) が実際の行列サイズと矛盾している可能性があります。\n",
        "[元のエラー]: ", err_msg,
        call. = FALSE
      )
    }

    # 数値/行列型エラーの翻訳 (これも日本語化されることがあるため追加)
    if (grepl("requires numeric/complex matrix/vector", err_msg) ||
        grepl("数値/複素数行列/ベクトル引数が必要です", err_msg)) {
      stop(
        "【データ型エラー】数値ベクトルまたは行列が必要な箇所に、別の型が渡されています。\n",
        "・原因: 観測データやインデックスが data.frame や list になっていませんか？\n",
        "[元のエラー]: ", err_msg,
        call. = FALSE
      )
    }

    # 未知のエラーはそのまま出力
    stop("【予期せぬエラー】\n", err_msg, call. = FALSE)
  })
}
#' Model Code Wrapper for RTMB
#'
#' @param expr A block of code containing model description.
#' @param env Environment to assign to the generated function.
#' @return A standard R function object taking (dat, par).
#' @export
model_code <- function(expr, env = parent.frame()) {
  raw_expr <- substitute(expr)

  # 修正点1: ユーザーが変数として quote() を渡した場合への対応
  # 例: my_ast <- quote({ Y ~ normal(0,1) }); model_code(my_ast)
  if (is.name(raw_expr)) {
    evaluated <- eval(raw_expr, envir = env)
    if (is.language(evaluated)) {
      raw_expr <- evaluated
    }
  }

  # 式を再帰的に走査し、`~` の記述を書き換える
  rewrite_formula <- function(x) {
    if (is.call(x)) {
      if (identical(x[[1]], as.name("~"))) {
        target <- x[[2]]
        dist_call <- x[[3]]

        # 修正点2: 右辺が関数呼び出しでない場合のエラーハンドリング
        # 例: Y ~ normal （カッコがない）と書かれた場合を防ぐ
        if (!is.call(dist_call)) {
          stop(sprintf("The right side of '~' must be a distribution function call. (e.g., %s( ... ))",
                       as.character(dist_call)), call. = FALSE)
        }

        dist_name <- as.character(dist_call[[1]])
        dist_args <- as.list(dist_call[-1])

        name_lpdf <- paste0(dist_name, "_lpdf")
        name_lpmf <- paste0(dist_name, "_lpmf")

        # 環境に存在する方を優先的に採用
        if (exists(name_lpdf, mode = "function", envir = env)) {
          actual_name <- name_lpdf
        } else if (exists(name_lpmf, mode = "function", envir = env)) {
          actual_name <- name_lpmf
        } else {
          actual_name <- name_lpdf # デフォルト
        }

        # lp <- lp + actual_name(target, args...) の純粋な構文木を作成
        new_call <- as.call(c(
          as.name("<-"),
          as.name("lp"),
          as.call(c(
            as.name("+"),
            as.name("lp"),
            as.call(c(as.name(actual_name), target, dist_args))
          ))
        ))
        return(new_call)
      }
      # 再帰的に要素を書き換え
      x[] <- lapply(x, rewrite_formula)
    }
    return(x)
  }

  processed_expr <- rewrite_formula(raw_expr)

  # ブロック {} の場合は中身を展開してフラットにする
  if (is.call(processed_expr) && identical(processed_expr[[1]], as.name("{"))) {
    expr_elements <- as.list(processed_expr)[-1]
  } else {
    expr_elements <- list(processed_expr)
  }

  # 修正点3: body_list の要素に意図しない名前が付かないよう unname で安全化
  # 関数の中身（ボディ）を構築: { getAll(dat, par); lp <- 0; ... ; return(lp) }
  body_list <- c(
    list(as.name("{")),
    quote(getAll(dat, par)),
    quote(lp <- 0),
    unname(expr_elements),
    quote(return(lp))
  )
  body_expr <- as.call(body_list)

  # 引数リスト `(dat, par)` を作成
  args <- as.pairlist(alist(dat = , par = ))
  fn_expr <- call("function", args, body_expr)

  # 関数の評価（作成）
  log_prob_fn <- eval(fn_expr, envir = env)

  # print_code メソッドなどのために元の構文木を保存
  attr(log_prob_fn, "raw_expr") <- raw_expr

  return(log_prob_fn)
}
#' Transformed Code Wrapper for RTMB
#'
#' @param expr A block of code containing calculations for transformed parameters.
#' @param env Environment to assign to the generated function.
#' @return A function taking (dat, par) that returns a named list.
#' @export
transformed_code <- function(expr, env = parent.frame()) {
  raw_expr <- substitute(expr)

  # 1. 中括弧 {} の中身をフラットにする
  if (is.call(raw_expr) && identical(raw_expr[[1]], as.name("{"))) {
    expr_elements <- as.list(raw_expr)[-1]
  } else {
    expr_elements <- list(raw_expr)
  }

  # 2. 最後の要素が list(...) かどうかを判定
  last_elem <- expr_elements[[length(expr_elements)]]
  is_explicit_return <- is.call(last_elem) && identical(last_elem[[1]], as.name("list"))

  if (is_explicit_return) {
    # 明示的に list(...) が書かれている場合、それを出力として採用
    ret_call <- last_elem
    # 重複評価を防ぐため、通常の実行フローから最後の list(...) を削除
    expr_elements <- expr_elements[-length(expr_elements)]

  } else {
    # 記述がない場合は従来通り自動抽出する
    find_assignments <- function(x) {
      if (is.call(x)) {
        if (identical(x[[1]], as.name("<-")) || identical(x[[1]], as.name("="))) {
          if (is.name(x[[2]])) return(as.character(x[[2]]))
        }
        return(unique(unlist(lapply(as.list(x), find_assignments))))
      }
      return(NULL)
    }
    defined_vars <- find_assignments(raw_expr)
    ret_list_args <- lapply(defined_vars, as.name)
    names(ret_list_args) <- defined_vars
    ret_call <- as.call(c(list(as.name("list")), ret_list_args))
  }

  # 3. 関数ボディの構築
  body_list <- c(
    list(as.name("{")),
    quote(getAll(dat, par)),
    unname(expr_elements),
    list(as.call(list(as.name("return"), ret_call)))
  )
  body_expr <- as.call(body_list)

  # 4. 関数オブジェクトの生成
  args <- as.pairlist(alist(dat = , par = ))
  fn_expr <- call("function", args, body_expr)
  fn <- eval(fn_expr, envir = env)
  attr(fn, "raw_expr") <- raw_expr

  return(fn)
}
#' データとパラメータの事前検証
#'
#' @description
#' `rtmb_model` にデータを渡す前に、R特有のデータ型（data.frameなど）が混入していないか、
#' および欠損値の有無などをチェックし、エラーや警告を出力します。
#'
#' @param dat_list モデルに渡すデータのリスト（通常、行列や数値ベクトルを含む）。
#' @param par_list `Dim()` で定義されたパラメータのリスト。
#'
#' @return 検証に成功した場合は不可視の `NULL` を返します。問題がある場合は `stop()` で処理を中断、または `warning()` を発出します。
#'
#' @details
#' RTMBの自動微分エンジンは純粋な `matrix` や `numeric` を要求します。
#' ユーザーが誤って `data.frame` を渡した場合、計算グラフの構築時に不可解なエラーが発生するため、
#' この関数で事前に捕捉します。
validate_data <- function(dat_list, par_list) {
  # 1. データフレームのチェック
  for (name in names(dat_list)) {
    if (is.data.frame(dat_list[[name]])) {
      stop(sprintf(
        "【エラー】データ '%s' がデータフレーム(data.frame)のまま渡されています。\n行列演算が失敗するため、as.matrix() で行列に変換してから渡してください。",
        name
      ), call. = FALSE)
    }
  }

  # 2. NAのチェック
  for (name in names(dat_list)) {
    if (any(is.na(dat_list[[name]]))) {
      warning(sprintf("【警告】データ '%s' に欠損値(NA)が含まれています。予期せぬ動作を引き起こす可能性があります。", name), call. = FALSE)
    }
  }

  invisible(NULL)
}


#' 安全なRTMBモデルの構築（エラーメッセージ翻訳付き）
#'
#' @description
#' `rtmb_model` をラップし、内部の `MakeADFun` 実行時に発生する C++/RTMB 由来の
#' 難解なエラーメッセージを、ユーザーが理解しやすい日本語のヒントに翻訳して出力します。
#'
#' @param data `validate_data` を通過したデータのリスト。
#' @param parameters `Dim()` で定義されたパラメータのリスト。
#' @param model `model_code({})` で定義された尤度や事前分布のコードブロック。
#' @param generate `transformed_code({})` で定義された生成量のコードブロック（省略可能）。
#'
#' @return 正常にコンパイルが完了した場合は、`rtmb_model` オブジェクト（R6クラスのインスタンス）を返します。
#'
#' @export
safe_rtmb_model <- function(data, parameters, model, generate = NULL) {
  # 事前検証を実行
  validate_data(data, parameters)

  tryCatch({
    # 実際のモデル構築処理
    obj <- rtmb_model(data, parameters, model, generate)
    return(obj)

  }, error = function(e) {
    err_msg <- conditionMessage(e)

    # ADクラス消失エラーの翻訳
    if (grepl("lost class attribute", err_msg) || grepl("Invalid argument to 'advector'", err_msg)) {
      stop(
        "【モデル構築エラー】自動微分(AD)の型が途中で消失しました。\n",
        "・原因: model_code 内で rep() や空の array() に対して for ループで逐次代入を行っている可能性があります。\n",
        "・対策: 行列のベクトル化計算を使用するか、初期化には numeric(M) などを利用してください。\n",
        "[元のエラー]: ", err_msg,
        call. = FALSE
      )
    }

    # 不正な演算エラーの翻訳
    if (grepl("illegal operation", err_msg) || grepl("not a valid 'advector'", err_msg)) {
      stop(
        "【モデル構築エラー】実行不可能な演算、または型の不整合が発生しました。\n",
        "・原因: 行列の掛け算(%*%)の左右で次元が合っていない、または Dim() の型指定 (CF_cov, lower_tri など) が実際の行列サイズと矛盾している可能性があります。\n",
        "[元のエラー]: ", err_msg,
        call. = FALSE
      )
    }

    # 数値/行列型エラーの翻訳
    if (grepl("requires numeric/complex matrix/vector", err_msg)) {
      stop(
        "【データ型エラー】数値ベクトルまたは行列が必要な箇所に、別の型が渡されています。\n",
        "・原因: 観測データやインデックスが data.frame や list になっていませんか？\n",
        "[元のエラー]: ", err_msg,
        call. = FALSE
      )
    }

    # 未知のエラーはそのまま出力
    stop("【予期せぬエラー】\n", err_msg, call. = FALSE)
  })
}


#' RTMBベースのGLMMラッパー関数
#'
#' @param formula lme4スタイルのフォーミュラ (例: Y ~ X + (1 + X | GID))
#' @param data データフレーム
#' @param family 分布族の文字列 ("gaussian", "poisson", "binomial", "bernoulli", "lognormal", "gamma", "student_t", "neg_binomial", "ordered")
#' @param laplace 変量効果をラプラス近似で周辺化するかどうか (デフォルト: FALSE)
#' @param prior 事前分布のハイパーパラメータのリスト
#' RTMBベースのGLMMラッパー関数
#'
#' @param formula lme4スタイルのフォーミュラ (例: Y ~ X + (1 + X | GID))
#' @param data データフレーム
#' @param family 分布族の文字列
#' @param laplace 変量効果をラプラス近似で周辺化するかどうか (デフォルト: FALSE)
#' @param prior 事前分布のハイパーパラメータのリスト
rtmb_glmer <- function(formula, data, family = "gaussian", laplace = FALSE,
                       prior = list(
                         beta_sd = 10,
                         tau_rate = 1,
                         sigma_rate = 1,
                         lkj_eta = 1.0,
                         shape_rate = 1,
                         phi_rate = 1
                       )) {

  if (!requireNamespace("lme4", quietly = TRUE)) {
    stop("フォーミュラの解析に 'lme4' パッケージが必要です。")
  }

  # 1. フォーミュラのパース
  parsed <- lme4::lFormula(
    formula,
    data = data,
    control = lme4::lmerControl(
      check.nobs.vs.nlev = "ignore",
      check.nobs.vs.nRE  = "ignore"
    )
  )

  # --- 応答変数Yの型変換（factor型・行列型への対応） ---
  Y <- model.response(parsed$fr)
  if (is.matrix(Y)) {
    if (ncol(Y) == 2 && family == "binomial") {
      trials <- as.numeric(Y[, 1] + Y[, 2])
      Y <- as.numeric(Y[, 1])
    } else if (ncol(Y) == 1) {
      Y <- as.numeric(Y[, 1])
      trials <- rep(1, length(Y))
    } else {
      stop("応答変数の行列形式が不正です。binomialの場合は cbind(成功数, 失敗数) を指定してください。")
    }
  } else {
    trials <- rep(1, length(Y))
    if (is.factor(Y)) {
      if (family %in% c("bernoulli", "binomial")) {
        Y <- as.numeric(Y) - 1
      } else {
        Y <- as.numeric(Y)
      }
    } else {
      Y <- as.numeric(Y)
    }
  }

  X <- parsed$X          # 固定効果のデザイン行列
  reTrms <- parsed$reTrms

  if (length(reTrms$Ztlist) > 1) {
    stop("現在、ラッパー関数は単一のグループ化変数のみに対応しています。")
  }

  # 固定効果と変量効果の名前を取得
  fixed_names <- colnames(X)
  fixed_names[fixed_names == "(Intercept)"] <- "Intercept"
  ranef_names <- parsed$reTrms$cnms[[1]]

  # 変量効果の情報の抽出
  Zt <- as.matrix(reTrms$Ztlist[[1]])
  group_idx <- as.integer(reTrms$flist[[1]])
  num_groups <- length(levels(reTrms$flist[[1]]))
  num_ranef <- nrow(Zt) / num_groups

  # 観測ごとの変量効果デザイン行列(N x num_ranef)を作成
  N <- length(Y)
  Z_mat <- matrix(0, nrow = N, ncol = num_ranef)
  for (i in 1:N) {
    g <- group_idx[i]
    rows <- ((g - 1) * num_ranef + 1):(g * num_ranef)
    Z_mat[i, ] <- Zt[rows, i]
  }

  # 2. dataの準備
  dat <- list(
    N = N,
    Y = Y,
    trials = trials,
    X = X,
    Z_mat = Z_mat,
    group_idx = group_idx,
    num_groups = num_groups,
    num_ranef = num_ranef,
    K = ncol(X),
    fam_name = family,
    prior_beta_sd    = prior$beta_sd,
    prior_tau_rate   = prior$tau_rate,
    prior_sigma_rate = prior$sigma_rate,
    prior_lkj_eta    = prior$lkj_eta,
    prior_shape_rate = prior$shape_rate,
    prior_phi_rate   = prior$phi_rate
  )

  # parameterの準備
  if (num_ranef == 1) {
    params <- list(
      beta = Dim(ncol(X)),
      tau  = Dim(num_ranef, lower = 0),
      r    = Dim(num_groups, random = TRUE)
    )
  } else {
    params <- list(
      beta     = Dim(ncol(X)),
      tau      = Dim(num_ranef, lower = 0),
      CF_Omega = Dim(c(num_ranef, num_ranef), type = "CF_corr"),
      r        = Dim(c(num_groups, num_ranef), random = TRUE)
    )
  }

  # 分布族に応じた追加パラメータの設定
  if (family %in% c("gaussian", "lognormal", "student_t")) {
    params$sigma <- Dim(1, lower = 0)
  }
  if (family == "student_t") {
    params$nu <- Dim(1, lower = 2) # 自由度は2以上を推奨
  }
  if (family == "gamma") {
    params$shape <- Dim(1, lower = 0)
  }
  if (family == "neg_binomial") {
    params$phi <- Dim(1, lower = 0) # dispersion parameter (size)
  }
  if (family == "ordered") {
    num_categories <- length(unique(Y))
    # カテゴリ数 - 1 のorderedパラメータが必要
    params$cutpoints <- Dim(num_categories - 1, type = "ordered")
  }

  # 3. モデルコードの動的構築
  # 選択された分布に応じた尤度（と固有の事前分布）のコードブロックを作成
  ll_expr <- switch(family,
                    "gaussian" = quote({
                      sigma ~ exponential(prior_sigma_rate)
                      for(i in 1:N) { Y[i] ~ normal(eta[i], sigma) }
                    }),
                    "lognormal" = quote({
                      sigma ~ exponential(prior_sigma_rate)
                      for(i in 1:N) { Y[i] ~ lognormal(eta[i], sigma) }
                    }),
                    "student_t" = quote({
                      sigma ~ exponential(prior_sigma_rate)
                      nu ~ exponential(0.1)
                      for(i in 1:N) { Y[i] ~ student_t(nu, eta[i], sigma) }
                    }),
                    "gamma" = quote({
                      shape ~ exponential(prior_shape_rate)
                      for(i in 1:N) { Y[i] ~ gamma(shape, shape / exp(eta[i])) }
                    }),
                    "bernoulli" = quote({
                      for(i in 1:N) { Y[i] ~ bernoulli_logit(eta[i]) }
                    }),
                    "binomial" = quote({
                      Y ~ binomial_logit(trials, eta)
                    }),
                    "poisson" = quote({
                      for(i in 1:N) { Y[i] ~ poisson(exp(eta[i])) }
                    }),
                    "neg_binomial" = quote({
                      phi ~ exponential(prior_phi_rate)
                      for(i in 1:N) { Y[i] ~ neg_binomial_2(exp(eta[i]), phi) }
                    }),
                    "ordered" = quote({
                      for(i in 1:N) { Y[i] ~ ordered_logistic(eta[i], cutpoints) }
                    })
  )

  # 共通部分を独立したブロックとして定義
  if (num_ranef > 1) {
    common_expr <- quote({
      # 事前分布
      beta ~ normal(0, prior_beta_sd)
      tau ~ exponential(prior_tau_rate)
      CF_Omega ~ lkj_CF_corr(prior_lkj_eta)

      # 変量効果の事前分布
      for (j in 1:num_groups) {
        r[j, ] ~ multi_normal_CF(rep(0, num_ranef), 1, CF_Omega)
      }

      # 線形予測子の計算
      eta <- as.vector(X %*% beta)
      for (i in 1:N) {
        eta[i] <- eta[i] + sum(Z_mat[i, ] * r[group_idx[i], ] * tau)
      }
    })
  }else{
    common_expr <- quote({
      # 事前分布
      beta ~ normal(0, prior_beta_sd)
      tau ~ exponential(prior_tau_rate)

      # 変量効果の事前分布
      r ~ normal(0, 1)

      # 線形予測子の計算
      eta <- as.vector(X %*% beta) + Z_mat[i,1] * r[group_idx[i]] * tau
    })
  }


  # 両方のブロックから外側の "{ }" を取り除き、中身の式（要素）をリストとして抽出
  common_list <- as.list(common_expr)[-1]
  ll_list <- as.list(ll_expr)[-1]

  model_ast <- as.call(c(list(as.name("{")), common_list, ll_list))

  model_expr <- eval(bquote(model_code(.(model_ast))))

  # 4. 生成量の構築
  if (num_ranef > 1) {
    generate_expr <- transformed_code({
      Omega <- CF_Omega %*% t(CF_Omega)
      Sigma <- diag(tau) %*% Omega %*% diag(tau)
    })
  }

  # 5. rtmb_model を呼び出してオブジェクトを返す
  if (num_ranef > 1) {
    obj <- rtmb_model(
      data = dat,
      parameters = params,
      model = model_expr,
      generate = generate_expr,
      par_names = list(beta = fixed_names, tau = ranef_names, Omega = ranef_names)
    )
  }else{
    obj <- rtmb_model(
      data = dat,
      parameters = params,
      model = model_expr,
      par_names = list(beta = fixed_names, tau = ranef_names)
    )
  }

  obj$formula <- formula
  obj$raw_data <- data
  obj$family <- family

  return(obj)
}
#' RTMBベースのGLMラッパー関数 (変量効果なし)
#'
#' @param formula フォーミュラ (例: Y ~ X1 + X2)
#' @param data データフレーム
#' @param family 分布族の文字列
#' @param prior 事前分布のハイパーパラメータのリスト
#' @export
rtmb_glm <- function(formula, data, family = "gaussian",
                     prior = list(
                       beta_sd = 10,
                       sigma_rate = 1,
                       shape_rate = 1,
                       phi_rate = 1
                     )) {

  # 1. フォーミュラのパース
  mf <- model.frame(formula, data)
  Y <- model.response(mf)
  X <- model.matrix(formula, mf)

  # 応答変数Yの型変換（factor型への対応）
  if (is.matrix(Y)) {
    if (ncol(Y) == 2 && family == "binomial") {
      trials <- as.numeric(Y[, 1] + Y[, 2]) # 試行回数 (成功 + 失敗)
      Y <- as.numeric(Y[, 1])               # 成功数
    } else if (ncol(Y) == 1) {
      Y <- as.numeric(Y[, 1])
      trials <- rep(1, length(Y))
    } else {
      stop("応答変数の行列形式が不正です。binomialの場合は cbind(成功数, 失敗数) を指定してください。")
    }
  } else {
    trials <- rep(1, length(Y))
    if (is.factor(Y)) {
      if (family %in% c("bernoulli", "binomial")) {
        Y <- as.numeric(Y) - 1  # 0, 1 に変換
      } else {
        Y <- as.numeric(Y)      # 1, 2, 3... に変換
      }
    } else {
      Y <- as.numeric(Y)
    }
  }

  N <- length(Y)
  fixed_names <- colnames(X)
  fixed_names[fixed_names == "(Intercept)"] <- "Intercept"

  # 2. dataの準備
  dat <- list(
    N = N,
    Y = Y,
    trials = trials,
    X = X,
    K = ncol(X),
    prior_beta_sd    = prior$beta_sd,
    prior_sigma_rate = prior$sigma_rate,
    prior_shape_rate = prior$shape_rate,
    prior_phi_rate   = prior$phi_rate
  )

  # 3. parameterの準備 (固定効果のみ)
  params <- list(
    beta = Dim(ncol(X))
  )

  # 分布族に応じた追加パラメータの設定
  if (family %in% c("gaussian", "lognormal", "student_t")) {
    params$sigma <- Dim(1, lower = 0)
  }
  if (family == "student_t") {
    params$nu <- Dim(1, lower = 2) # 自由度は2以上を推奨
  }
  if (family == "gamma") {
    params$shape <- Dim(1, lower = 0)
  }
  if (family == "neg_binomial") {
    params$phi <- Dim(1, lower = 0) # dispersion parameter
  }
  if (family == "ordered") {
    num_categories <- length(unique(Y))
    params$cutpoints <- Dim(num_categories - 1, type = "ordered")
  }

  # 4. モデルコードの動的構築
  ll_expr <- switch(family,
                    "gaussian" = quote({
                      sigma ~ exponential(prior_sigma_rate)
                      for(i in 1:N) { Y[i] ~ normal(eta[i], sigma) }
                    }),
                    "lognormal" = quote({
                      sigma ~ exponential(prior_sigma_rate)
                      for(i in 1:N) { Y[i] ~ lognormal(eta[i], sigma) }
                    }),
                    "student_t" = quote({
                      sigma ~ exponential(prior_sigma_rate)
                      nu ~ exponential(0.1)
                      for(i in 1:N) { Y[i] ~ student_t(nu, eta[i], sigma) }
                    }),
                    "gamma" = quote({
                      shape ~ exponential(prior_shape_rate)
                      for(i in 1:N) { Y[i] ~ gamma(shape, shape / exp(eta[i])) }
                    }),
                    "bernoulli" = quote({
                      for(i in 1:N) { Y[i] ~ bernoulli_logit(eta[i]) }
                    }),
                    "binomial" = quote({
                      for(i in 1:N) { Y[i] ~ binomial_logit(trials[i], eta[i]) }
                    }),
                    "poisson" = quote({
                      for(i in 1:N) { Y[i] ~ poisson(exp(eta[i])) }
                    }),
                    "neg_binomial" = quote({
                      phi ~ exponential(prior_phi_rate)
                      for(i in 1:N) { Y[i] ~ neg_binomial_2(exp(eta[i]), phi) }
                    }),
                    "ordered" = quote({
                      for(i in 1:N) { Y[i] ~ ordered_logistic(eta[i], cutpoints) }
                    })
  )

  # 変量効果を除外した線形予測子
  common_expr <- quote({
    beta ~ normal(0, prior_beta_sd)
    eta <- as.vector(X %*% beta)
  })

  common_list <- as.list(common_expr)[-1]
  ll_list <- as.list(ll_expr)[-1]

  model_ast <- as.call(c(list(as.name("{")), common_list, ll_list))
  model_expr <- eval(bquote(model_code(.(model_ast))))

  # 5. rtmb_model を呼び出してオブジェクトを返す
  obj <- rtmb_model(
    data = dat,
    parameters = params,
    model = model_expr,
    generate = NULL,
    par_names = list(beta = fixed_names)
  )

  obj$formula <- formula
  obj$raw_data <- data
  obj$family <- family

  return(obj)
}
#' 探索的因子分析 (Bayesian EFA) 超高速版ラッパー
#'
#' @param data 観測データフレームまたは行列 (N x P)
#' @param n_factors 因子の数 (K)
#' @param prior 事前分布のハイパーパラメータのリスト
#' 探索的因子分析 (Bayesian EFA) 安定・潜在変数モデル版ラッパー
rtmb_fa <- function(data, n_factors = 1,
                    prior = list(mu_sd = 10, lambda_sd = 3, psi_rate = 1)) {

  Y <- as.matrix(data)
  N <- nrow(Y)
  P <- ncol(Y)
  K <- n_factors

  # --- 変数名の取得 ---
  var_names <- colnames(data)
  if (is.null(var_names)) var_names <- paste0("V", 1:P)

  if (K >= P) {
    stop("因子の数(K)は観測変数の数(P)より小さくする必要があります。")
  }

  # 1. データの準備
  dat <- list(
    N = N,
    P = P,
    K = K,
    Y = Y,
    prior_mu_sd     = prior$mu_sd,
    prior_lambda_sd = prior$lambda_sd,
    prior_psi_rate  = prior$psi_rate
  )

  # 2. パラメータの定義 (thetaをランダム効果として追加)
  params <- list(
    mu     = Dim(P),
    Lambda = Dim(c(P, K), type = "lower_tri"),
    psi    = Dim(P, lower = 0),
    theta  = Dim(c(N, K), random = TRUE)
  )

  # 3. モデルの構築 (潜在変数アプローチ)
  model_expr <- model_code({
    # 事前分布
    mu ~ normal(0, prior_mu_sd)
    Lambda ~ normal(0, prior_lambda_sd)
    psi ~ exponential(prior_psi_rate)
    theta ~ normal(0, 1)

    # 尤度計算
    for (n in 1:N) {
      Y_bar <- mu + Lambda %*% theta[n, ]
      Y[n, ] ~ normal(Y_bar, sqrt(psi))
    }
  })

  # 4. 生成量 (共通性と因子スコアの抽出)
  gq_expr <- transformed_code({
    Sigma <- Lambda %*% t(Lambda) + diag(psi)
    var_total <- diag(Sigma)
    var_common <- rowSums(Lambda^2)
    communality <- var_common / var_total
    list(communality=communality)
  })

  # 5. モデルオブジェクトの生成
  obj <- rtmb_model(
    data       = dat,
    parameters = params,
    model      = model_expr,
    generate   = gq_expr,
    par_names  = list(mu = var_names, Lambda = var_names, psi = var_names)
  )

  return(obj)
}
#' 相関行列 (多変量正規分布) 推定ラッパー
#'
#' @param data 観測データフレームまたは行列 (N x P)
#' @param prior 事前分布のハイパーパラメータのリスト
#' @export
rtmb_cor <- function(data, prior = list(lkj_eta = 1.0, mu_sd = 10, sigma_rate = 1.0)) {

  Y <- as.matrix(data)
  N <- nrow(Y)
  P <- ncol(Y)

  var_names <- colnames(data)
  if (is.null(var_names)) var_names <- paste0("V", 1:P)

  dat <- list(
    N = N,
    P = P,
    Y = Y,
    prior_lkj_eta    = prior$lkj_eta,
    prior_sigma_rate = prior$sigma_rate,
    prior_mu_sd      = prior$mu_sd
  )

  params <- list(
    mu       = Dim(P),
    sigma    = Dim(P, lower = 0),
    CF_Omega = Dim(c(P, P), type = "CF_corr")
  )

  model_expr <- model_code({
    # 事前分布
    mu ~ normal(0, prior_mu_sd)
    sigma ~ exponential(prior_sigma_rate)
    CF_Omega ~ lkj_CF_corr(prior_lkj_eta)

    for(i in 1:N) {
      Y[i, ] ~ multi_normal_CF(mu, sigma, CF_Omega)
    }
  })

  gq_expr <- transformed_code({
    Omega <- CF_Omega %*% t(CF_Omega)
  })

  obj <- rtmb_model(
    data       = dat,
    parameters = params,
    model      = model_expr,
    generate   = gq_expr,
    par_names  = list(mu = var_names, sigma = var_names, Omega = var_names)
  )

  return(obj)
}
