#' RTMB model object
#'
#' @name RTMB_Model-class
#' @rdname RTMB_Model-class
#'
#' @description
#' An R6 class representing a Bayesian model built with RTMB.
#' This class stores model components and provides methods for
#' building the automatic differentiation object, optimizing the
#' posterior, and drawing posterior samples.
#'
#'
#' @field data Named list containing observation data.
#' @field par_list Evaluated list of parameter definitions.
#' @field log_prob Executable function for likelihood and prior calculations.
#' @field transform Function for calculating transformed parameters.
#' @field generate Function for calculating generated quantities.
#' @field par_names List of variable names corresponding to parameter dimensions.
#' @field pl_full Complete parameter list with expanded constraints and dimension information used internally.
#' @field formula Formula used for model generation (if created via a wrapper function).
#' @field requested_contrasts Character; user-requested contrast setting (e.g. "treatment").
#' @field contrasts Character; internal contrast setting used for fitting (e.g. "sum").
#' @field raw_data Data frame; the original data used for the model.
#' @field family Character string of the distribution family (if created via a wrapper function).
#' @field init List or numeric vector of initial values.
#' @field view Character vector of variable names to prioritize in summary.
#' @field code Original model AST generated by `rtmb_code()`.
#' @field map A list specifying parameter mappings for fixing values (e.g., via null_model).
#' @field prior_correction Numeric value storing the log-density of the fixed parameter for Bayes Factor correction.
#' @field type Character; the type of the model (e.g. 'lmer', 'glm', 'table', 'ttest', 'corr', 'mediation').
#' @field extra List; used to store auxiliary data (like term assignments, factors, test results) needed by methods such as classic().
#'
#' @import RTMB
#' @export
RTMB_Model <- R6::R6Class(
  classname = "RTMB_Model",
  public = list(
    data = NULL,
    par_list = NULL,
    log_prob = NULL,
    transform = NULL,
    generate = NULL,
    par_names = NULL,
    pl_full = NULL,
    formula = NULL,
    raw_data = NULL,
    family = NULL,
    init = NULL,
    view = NULL,
    code = NULL,
    map = NULL,
    type = NULL,
    extra = NULL,
    contrasts = NULL,
    requested_contrasts = NULL,
    prior_correction = 0,

    # 1. Constructor
    #' @description Create a new `RTMB_Model` object.
    #' @param data Named list containing observation data.
    #' @param par_list Evaluated list of parameter definitions.
    #' @param log_prob Executable function for likelihood and prior calculations.
    #' @param transform Function for calculating transformed parameters (optional).
    #' @param generate Function for calculating generated quantities (optional).
    #' @param par_names List of variable names corresponding to parameter dimensions.
    #' @param init List or numeric vector of initial values.
    #' @param view Character vector of variable names to prioritize in summary.
    #' @param code Original model AST generated by `rtmb_code()`.
    initialize = function(data, par_list, log_prob,
                          transform = NULL, generate = NULL, par_names = NULL,
                          init = NULL, view = NULL, code = NULL) {
      self$data <- data
      self$par_names <- par_names
      self$init <- init
      self$view <- view
      self$code <- code
      self$par_list <- lapply(par_list, function(x) {
        if (typeof(x) %in% c("language", "symbol")) {
          eval(x, envir = self$data, enclos = parent.frame())
        } else {
          x
        }
      })
      self$log_prob <- log_prob
      self$transform <- transform
      self$generate <- generate

      self$pl_full <- parse_parameters(self$par_list, self$par_names)
      names(self$pl_full$init) <- self$pl_full$names

      # Changed to go through prepare_init
      init_vec <- self$prepare_init(self$init)
      self$init <- init_vec
      test_para <- constrained_vector_to_list(init_vec, self$par_list)

      test_val <- tryCatch(
        {
          if (!is.null(self$transform)) {
            test_tran <- self$transform(self$data, test_para)
            test_para <- c(test_para, test_tran)
          }
          self$log_prob(self$data, test_para)
        },
        error = function(e) {
          stop("An error occurred during the test execution of the R function (log_prob).\n[Error]: ",
            e$message,
            "\n  * Possible cause: Inappropriate initial parameter values may lead to uncomputable likelihoods (Inf or NaN).",
            "\n  * Solution: Set appropriate initial values within the domain (e.g., >0 for variance) via the 'init' argument, or reconsider the data scaling.",
            call. = FALSE
          )
        }
      )

      if (!is.numeric(test_val) || length(test_val) != 1) {
        stop("log_prob must return a single numeric value (scalar).")
      }

      if (!is.null(self$transform)) {
        test_tran <- tryCatch(
          {
            self$transform(self$data, test_para)
          },
          error = function(e) {
            stop("An error occurred during the test execution of the R function (transform).\n[Error]: ",
              e$message,
              call. = FALSE
            )
          }
        )

        if (!is.null(test_tran)) {
          if (!is.list(test_tran)) {
            stop("transform must return a list.", call. = FALSE)
          }
          if (length(test_tran) > 0 && (is.null(names(test_tran)) || any(names(test_tran) == ""))) {
            stop("transform must return a named list.", call. = FALSE)
          }
        }
      }

      if (!getOption("BayesRTMB.silent", FALSE)) cat("Checking RTMB setup...\n")
      test_ad <- self$build_ad_obj(init = init_vec, laplace = FALSE, jacobian_target = "all")
      test_gr <- tryCatch(test_ad$ad_obj$gr(test_ad$ad_obj$par), error = function(e) e)
      if (inherits(test_gr, "error")) {
        stop("An error occurred during gradient calculation in MakeADFun.\n[Error]: ",
          test_gr$message,
          call. = FALSE
        )
      }
    },

    # Helper method to format and complement initial values (uses self$init if no arguments are provided)
    #' @description Prepare and format initial values for the model parameters.
    #' @param init_arg Optional list or numeric vector of initial values. If NULL, defaults to `self$init` or random generation.
    #' @return A flat numeric vector of constrained initial values.
    prepare_init = function(init_arg) {
      target_init <- if (!is.null(init_arg)) init_arg else self$init

      if (is.null(target_init)) {
        return(generate_random_init(self$pl_full, self$par_list, range = 2))
      }

      # When a named list is provided (partial initial value specification)
      if (is.list(target_init)) {
        # 1. First, initialize everything with random values and convert to list format
        base_vec <- generate_random_init(self$pl_full, self$par_list, range = 2)
        base_list <- constrained_vector_to_list(base_vec, self$par_list)

        # 2. Overwrite only the parameters specified by the user
        for (name in names(target_init)) {
          if (name %in% names(base_list)) {
            base_list[[name]] <- as.numeric(target_init[[name]])
          } else {
            warning(sprintf("The initial value specified for '%s' does not exist in the model.", name), call. = FALSE)
          }
        }
        # 3. Return to a complete flat vector and return
        return(unlist(base_list, use.names = FALSE))
      }

      # When a vector is provided (full specification)
      if (is.numeric(target_init)) {
        return(target_init)
      }

      stop("init must be specified as a named list or a numeric vector.")
    },

    #' @description Get the current parameters as a named list.
    #' @param init Optional numeric vector or list of initial values. If NULL, uses the model's current initial values.
    #' @return A named list of constrained parameters.
    get_par_list = function(init = NULL) {
      init_vec <- self$prepare_init(init)
      return(constrained_vector_to_list(init_vec, self$par_list))
    },

    #' @description Get the RTMB automatic differentiation object.
    #' @param ... Arguments passed to \code{build_ad_obj}.
    #' @return A TMB objective object (ad_obj).
    get_ad_obj = function(...) {
      return(self$build_ad_obj(...)$ad_obj)
    },

    #' @description Convert a list of constrained parameters to unconstrained space.
    #' @param par_list_constrained A named list of parameters in their natural space.
    #' @return A named list of parameters in unconstrained space.
    to_unconstrained = function(par_list_constrained) {
      return(to_unconstrained(par_list_constrained, self$par_list))
    },

    #' @description Convert a list of unconstrained parameters to constrained (natural) space.
    #' @param par_list_unconstrained A named list of parameters in unconstrained space.
    #' @return A named list of parameters in constrained space.
    to_constrained = function(par_list_unconstrained) {
      return(to_constrained(par_list_unconstrained, self$par_list))
    },

    #' @description Convert a flat unconstrained vector to a named list.
    #' @param vec A numeric vector in unconstrained space.
    #' @return A named list of unconstrained parameters.
    unconstrained_vector_to_list = function(vec) {
      return(unconstrained_vector_to_list(vec, self$par_list))
    },

    #' @description Convert a flat constrained vector to a named list.
    #' @param vec A numeric vector in constrained space.
    #' @return A named list of constrained parameters.
    constrained_vector_to_list = function(vec) {
      return(constrained_vector_to_list(vec, self$par_list))
    },

    #' @description Calculate Satterthwaite degrees of freedom for parameters.
    #' @param ad_obj An RTMB objective object at the optimum.
    #' @param idx_fix_active Integer vector; indices of active fixed parameters in the full unconstrained vector.
    #' @param L_u_total Integer; total length of the full unconstrained parameter vector.
    #' @param opt_par Optional numeric vector of optimized parameters.
    #' @param max_df Numeric; maximum allowed degrees of freedom. Default is NULL.
    #' @param silent Logical; whether to suppress informational messages. Default is FALSE.
    #' @param return_sensitivities Logical; if TRUE, returns Hessian sensitivities and V for delta method.
    #' @return A numeric vector of estimated degrees of freedom (length = L_u_total). Inf for random effects.
    calculate_satterthwaite_df = function(ad_obj, idx_fix_active = NULL, L_u_total = NULL, opt_par = NULL, max_df = NULL, silent = FALSE, return_sensitivities = FALSE) {
      .calculate_satterthwaite_df_impl(self, private, ad_obj, idx_fix_active, L_u_total, opt_par, max_df, silent, return_sensitivities)
    },

    #' @description Calculate Satterthwaite degrees of freedom for integrated fixed effects (REML).
    #' @param ad_obj An RTMB objective object.
    #' @param opt_par Numeric vector of optimized variance components.
    #' @param beta_idx Integer vector; indices of fixed effects within the random effects vector.
    #' @param silent Logical; whether to suppress informational messages. Default is FALSE.
    #' @param return_sensitivities Logical; if TRUE, returns Hessian sensitivities and delta-method components.
    #' @return A numeric vector of estimated degrees of freedom for the fixed effects.
    calculate_reml_satterthwaite_df = function(ad_obj, opt_par, beta_idx, silent = FALSE, return_sensitivities = FALSE) {
      .calculate_reml_satterthwaite_df_impl(self, private, ad_obj, opt_par, beta_idx, silent, return_sensitivities)
    },

    #' @description Build the RTMB automatic differentiation object.
    #' @param init Optional numeric vector or list of initial values for the parameters. Default is NULL.
    #' @param laplace Logical; whether to use Laplace approximation to marginalize random effects. Default is FALSE.
    #' @param jacobian_target Character string specifying which parameters to apply Jacobian adjustments to:
    #' \itemize{
    #'   \item \code{"all"}: Apply to all parameters (standard for Bayesian MCMC).
    #'   \item \code{"random"}: Apply only to parameters with \code{random = TRUE} (standard for Laplace approximation/REML).
    #'   \item \code{"none"}: No Jacobian adjustment (standard for Maximum Likelihood estimation).
    #' }
    #' Default is "none".
    #' @param map Optional list specifying parameters to fix. Passed directly to MakeADFun. Default is NULL.
    #' @param .marginal_vars Internal use for profiling marginalized parameters.
    #' @return An RTMB objective object (ad_obj).
    build_ad_obj = function(init = NULL, laplace = FALSE, jacobian_target = "none", map = NULL, .marginal_vars = NULL) {
      target_map <- if (is.null(map)) {
        self$map
      } else {
        utils::modifyList(as.list(self$map), as.list(map))
      }

      random_effs <- if (!is.null(.marginal_vars)) {
        .marginal_vars
      } else {
        names(self$par_list)[sapply(self$par_list, function(x) isTRUE(x$random))]
      }

      # Exclude random components where all elements are NA in fixed/map
      if (!is.null(target_map)) {
        random_effs <- random_effs[vapply(random_effs, function(nm) {
          m <- target_map[[nm]]
          if (is.null(m)) return(self$par_list[[nm]]$unc_length > 0)
          any(!is.na(m))
        }, logical(1))]
        
        target_map <- lapply(target_map, function(m) {
          if (is.null(m)) return(NULL)
          factor(as.character(m))
        })
      }

      use_random <- if (laplace && length(random_effs) > 0) random_effs else NULL

      current_init <- self$prepare_init(init)
      current_init_list <- constrained_vector_to_list(current_init, self$par_list)
      init_unc_list <- to_unconstrained(current_init_list, self$par_list)

      pl_full_local <- self$pl_full
      par_list_local <- self$par_list
      log_prob_local <- self$log_prob
      data_local <- self$data

      f_ad <- private$.build_f_ad(
        data_local = data_local,
        par_list_local = par_list_local,
        log_prob_local = log_prob_local,
        transform_local = self$transform,
        jacobian_target = jacobian_target,
        adreport = TRUE
      )

      ad_obj <- tryCatch(
        {
          RTMB::MakeADFun(
            func = f_ad,
            parameters = init_unc_list,
            random = use_random,
            map = target_map,
            silent = TRUE
          )
        },
        error = function(e) {
          stop("Failed to setup MakeADFun.\n[Error]: ", e$message, call. = FALSE)
        }
      )

      return(list(
        ad_obj = ad_obj,
        pl_full = pl_full_local,
        use_random = use_random
      ))
    },

    # 3. Maximum Likelihood / MAP Estimation Method
    #' @description Perform Maximum Likelihood or Maximum A Posteriori (MAP) estimation.
    #' @param laplace Logical; whether to use Laplace approximation for random effects. Default is TRUE.
    #' @param init Optional initial values for parameters (numeric vector or list).
    #' @param num_estimate Integer; Number of multi-start optimization runs. Default is 1.
    #' @param control A list of control settings passed to the optimizer.
    #' @param optimizer Character; The optimizer to use: "nlminb" (default) or "optim".
    #' @param method Character; The method for "optim" (e.g., "BFGS", "L-BFGS-B").
    #' @param map Optional list specifying parameters to fix (factors).
    #' @param fixed Optional list specifying parameter values to fix.
    #' @param se Logical; whether to estimate standard errors and confidence intervals. Default is TRUE.
    #' @param se_method Character; The method for CI estimation: "wald" (Wald CI) or "sampling" (Simulation-based).
    #' @param num_samples Integer; number of samples to draw when se_method is "sampling". Default is 1000.
    #' @param seed Integer; random seed for sampling.
    #' @param df Degrees of freedom for the t-distribution used in confidence intervals and summary.
    #' @param df_method Character; Method for calculating degrees of freedom ("bw", "satterthwaite", "Inf").
    #' @param empirical Logical or character; whether to use empirical Bayes / REML.
    #' @param REML Logical; whether to use Restricted Maximum Likelihood. Default is FALSE.
    #' @param marginal Character vector of parameters to marginalize out (random effects).
    #' @param view Character vector of parameter names to prioritize in summary display.
    #' @param is_classic Logical; Internal use.
    #' @param target_vars Character vector; Internal use.
    #' @param .return_object Character; Internal use.
    #' @param ci_method Alias for `se_method`.
    #' @param se_sampling Alias for `se_method = "sampling"`.
    #' @param df_pars Alias for `marginal`.
    #' @param views Alias for `view`.
    #' @param ... Additional arguments passed to Classic_Fit constructor.
    #' @return A fitted `MAP_Fit` or `Classic_Fit` object.
    optimize = function(laplace = TRUE, init = NULL, num_estimate = 1, control = list(),
                        optimizer = "nlminb", method = "BFGS", map = NULL, fixed = NULL,
                        se = TRUE, se_method = c("wald", "sampling"), 
                        num_samples = 1000, seed = 123,
                        df = NULL, df_method = NULL, 
                        empirical = FALSE, REML = FALSE, marginal = "auto", 
                        view = NULL, 
                        # --- Internal and compatibility aliases ---
                        is_classic = FALSE, target_vars = NULL, .return_object = "MAP",
                        ci_method = NULL, se_sampling = NULL, df_pars = NULL, views = NULL, ...) {
      .optimize_impl(self, private, laplace, init, num_estimate, control,
                     optimizer, method, map, fixed, se, se_method, 
                     num_samples, seed, df, df_method, 
                     empirical, REML, marginal, view, 
                     is_classic, target_vars, .return_object,
                     ci_method, se_sampling, df_pars, views, ...)
    },


    # 3.5. Classic Frequentist Inference Method
    #' @description Perform frequentist inference (REML/ML) with model-appropriate degrees of freedom.
    #' @param df Numeric/Inf for specific degrees of freedom. If NULL (default), determined by `df_method`.
    #' @param marginal Character vector of parameters to be treated as fixed effects for REML calculation. Default is "auto" (uses wrapper-defined targets if available). Use "none" to disable.
    #' @param df_pars Alias for `marginal` (for backward compatibility).
    #' @param REML Logical; whether to use Restricted Maximum Likelihood. Default is TRUE.
    #' @param view Character vector of parameters to prioritize in the summary output.
    #' @param views Alias for \code{view}.
    #' @param map Optional list specifying parameters to fix.
    #' @param fixed Optional list specifying parameter values to fix.
    #' @param df_method Character; Method for calculating degrees of freedom. Options:
    #' \itemize{
    #'   \item \code{"bw"} (default): Between-Within method for simple models, automatically switches to Satterthwaite for mixed models.
    #'   \item \code{"satterthwaite"}: Satterthwaite approximation (computationally intensive).
    #'   \item \code{"Inf"}: Use z-distribution (infinite degrees of freedom).
    #' }
    #' @param ... Additional arguments passed to $optimize().
    #' @return A `Classic_Fit` object.
    classic = function(df = NULL, df_method = NULL, REML = TRUE, marginal = "auto", 
                       view = NULL, map = NULL, fixed = NULL, 
                       # --- Compatibility aliases ---
                       df_pars = NULL, views = NULL, ...) {
      .classic_impl(self, private, df, df_method, REML, marginal, 
                    view, map, fixed, df_pars, views, ...)
    },

    # 4. MCMC NUTS Sampling Method
    #' @description Draw posterior samples from the model.
    #' @param sampling Number of sampling iterations. Default is 1000.
    #' @param warmup Number of warmup iterations. Default is 1000.
    #' @param chains Number of MCMC chains. Default is 4.
    #' @param thin Thinning interval. Default is 1.
    #' @param seed Random seed.
    #' @param delta Target acceptance rate for HMC/NUTS. Default is 0.8.
    #' @param max_treedepth Maximum tree depth for HMC/NUTS. Default is 10.
    #' @param parallel Logical; whether to run chains in parallel. Default is FALSE.
    #' @param laplace Logical; whether to use Laplace approximation. Default is FALSE.
    #' @param init Optional initial values for parameters.
    #' @param init_jitter sd of randomize initial values for parameters.
    #' @param save_csv Optional list for saving MCMC results. e.g., list(name = "model", dir = "BayesRTMB_mcmc").
    #' @param map Optional list specifying parameters to fix (factors).
    #' @param fixed Optional list specifying parameter values to fix.
    #' @return A fitted `MCMC_Fit` object.
    sample = function(sampling = 1000, warmup = 1000, chains = 4,
                      thin = 1, seed = sample.int(1e6, 1),
                      delta = 0.8, max_treedepth = 10,
                      parallel = FALSE, laplace = FALSE,
                      init = NULL, init_jitter = 0.1, save_csv = NULL,
                      map = NULL, fixed = NULL) {
      .sample_impl(self, private, sampling, warmup, chains, thin, seed, delta, 
                   max_treedepth, parallel, laplace, init, init_jitter, 
                   save_csv, map, fixed)
    },

    #' @description Run Automatic Differentiation Variational Inference (ADVI).
    #' @param iter Integer; fixed number of iterations for the optimization. Default is 3000.
    #' @param tol_rel_obj Numeric; relative tolerance for the ELBO change to determine convergence. Default is 0.005.
    #' @param window_size Integer; window size for median smoothing in the convergence check. Default is 100.
    #' @param num_samples Integer; number of posterior samples to generate from the fitted variational distribution. Default is 1000.
    #' @param num_estimate Integer; number of times to run the VB estimation (treated as chains). Default is 4.
    #' @param alpha Numeric; learning rate for the Adam optimizer. Default is 0.01.
    #' @param laplace Logical; whether to use Laplace approximation to marginalize random effects. Default is FALSE.
    #' @param print_freq Integer; iterations interval for progress output. Set to 0 to disable. Default is 1000.
    #' @param method Character; method of Variational Inference. Default is "meanfield".
    #' @param parallel Logical; whether to run estimations in parallel. Default is FALSE.
    #' @param seed Integer; random seed for reproducibility.
    #' @param init Optional numeric vector or list for initial parameter values. Default is NULL.
    #' @param save_csv Optional list for saving VB results. e.g., list(name = "model", dir = "BayesRTMB_vb").
    #' @param map Optional list specifying parameters to fix (factors).
    #' @param fixed Optional list specifying parameter values to fix.
    #' @return A fitted `VB_Fit` object containing posterior samples and diagnostic information.
    variational = function(iter = 3000,
                           tol_rel_obj = 0.005, window_size = 100,
                           num_samples = 1000, num_estimate = 4, alpha = 0.01,
                           laplace = FALSE, print_freq = 1000,
                           method = c("meanfield", "fullrank", "hybrid"), parallel = FALSE,
                           seed = sample.int(1e6, 1), init = NULL, save_csv = NULL,
                           map = NULL, fixed = NULL) {
      .variational_impl(self, private, iter, tol_rel_obj, window_size, num_samples, 
                        num_estimate, alpha, laplace, print_freq, method, 
                        parallel, seed, init, save_csv, map, fixed)
    },


    # 5. Print model code method
    #' @description Print model code or model structure.
    #' @return The object itself, invisibly.
    print_code = function() {
      .print_code_impl(self, private)
    },

    #' @description Print the internal log-probability function.
    #' @return The object itself, invisibly.
    print_log_prob = function() {
      if (is.null(self$log_prob)) {
        cat("log_prob is not available.\n")
        return(invisible(self))
      }

      # Extract the internal function from the error-handling wrapper if it exists
      fn <- self$log_prob
      if (exists("comp_model", envir = environment(fn))) {
        fn <- get("comp_model", envir = environment(fn))
      }

      cat("=== RTMB Model: log_prob (Internal Function) ===\n")
      print(fn)
      return(invisible(self))
    },

    #' @description Print the internal transformation function.
    #' @return The object itself, invisibly.
    print_transform = function() {
      if (is.null(self$transform)) {
        cat("transform is not available.\n")
        return(invisible(self))
      }

      # Extract the internal function from the error-handling wrapper if it exists
      fn <- self$transform
      if (exists("comp_transform", envir = environment(fn))) {
        fn <- get("comp_transform", envir = environment(fn))
      }

      cat("=== RTMB Model: transform (Internal Function) ===\n")
      print(fn)
      return(invisible(self))
    },

    #' @description Print the internal generation function.
    #' @return The object itself, invisibly.
    print_generate = function() {
      if (is.null(self$generate)) {
        cat("generate is not available.\n")
        return(invisible(self))
      }

      # Extract the internal function from the error-handling wrapper if it exists
      fn <- self$generate
      if (exists("comp_generate", envir = environment(fn))) {
        fn <- get("comp_generate", envir = environment(fn))
      }

      cat("=== RTMB Model: generate (Internal Function) ===\n")
      print(fn)
      return(invisible(self))
    },

    #' @description Automatically detect and count the number of independent data points (observations).
    #' @return Integer; total number of observations, or NULL if model code is missing.
    get_n_obs = function() {
      .get_n_obs_impl(self, private)
    },

    #' @description Create a model with fixed parameters.
    #' @param fixed A named list of parameter values to fix.
    #' @param silent Logical; whether to suppress informational messages. Default is FALSE.
    #' @return A new RTMB_Model object.
    fixed_model = function(fixed = list(), silent = FALSE) {
      return(private$.apply_constraints(fixed, silent = silent))
    },

    #' @description Create a null model by fixing specified parameters.
    #' @param target Parameter name to fix.
    #' @param value Numeric value to fix parameter to. Default is 0.
    #' @param target_vars Character vector of parameter names to remove priors from (for frequentist inference).
    #' @param silent Logical; whether to suppress informational messages. Default is FALSE.
    #' @return A new RTMB_Model object.
    null_model = function(target = NULL, value = 0, target_vars = NULL, silent = FALSE) {
      if (!is.null(target_vars)) {
        new_model <- self$clone()
        if (!is.null(self$code)) {
          new_model$code <- as.list(self$code)
          for (v in target_vars) {
            new_model$code$model <- remove_prior_from_ast(new_model$code$model, v, self$par_names[[v]])
          }
        }
        return(new_model)
      }
      
      if (is.null(target)) return(self)
      fixed <- list()
      fixed[[target]] <- value
      return(self$fixed_model(fixed, silent = silent))
    },

    #' @description Evaluate the univariate prior density contribution of a specific parameter.
    #' @param p_name Flattened parameter name (e.g., "beta[1]").
    #' @param u_val Value in unconstrained space.
    #' @param par_list Optional parameter list (constrained) to use for evaluation.
    #' @return Numeric log-prior density (unconstrained).
    evaluate_univariate_prior = function(p_name, u_val, par_list = NULL) {
      .evaluate_univariate_prior_impl(self, private, p_name, u_val, par_list, caller_env = parent.frame())
    }
  ),

  private = list(
    .simple_jacobian = function(f, x, h = 1e-4) {
      p <- length(x)
      f0 <- f(x)
      res <- matrix(0, nrow = length(f0), ncol = p)
      for (i in 1:p) {
        h_i <- max(abs(x[i]), 1e-4) * h
        x_plus <- x
        x_minus <- x
        x_plus[i] <- x[i] + h_i
        x_minus[i] <- x[i] - h_i
        res[, i] <- (f(x_plus) - f(x_minus)) / (2 * h_i)
      }
      return(res)
    },
    # --- Common patterns for REML and parameter classification ---
    fix_patterns = c("Intercept", "Intercept_c", "b", "mean", "prob", "beta", "mu", "delta", "diff", "mean_diff"),
    var_patterns = c("sigma", "sd", "rho", "rho_resid", "L_resid", "corr", "CF_corr", "cov", "CF_cov", "cutpoints", "shape", "phi", "nu", "z", "lambda", "tau", "theta", "alpha", "omega", "kappa"),

    # --- Internal helper for index computation ---
    .compute_active_indices = function(target_map = NULL) {
      idx_fix_active <- integer(0)
      factor_levels_seen <- list()
      opt_par_curr <- 1
      
      map_to_use <- if (!is.null(target_map)) target_map else self$map
      
      for (name in names(self$par_list)) {
        p <- self$par_list[[name]]
        L_u <- p$unc_length
        m <- if (!is.null(map_to_use[[name]])) map_to_use[[name]] else factor(1:L_u)
        
        # Identify indices that are not NA (i.e., estimated)
        idx_active_local <- which(!is.na(m))
        if (length(idx_active_local) > 0) {
          # Check for shared levels (identical factors)
          lvl_names <- as.character(m[idx_active_local])
          for (lvl in unique(lvl_names)) {
            pos_in_active <- which(lvl_names == lvl)
            # The first occurrence of this level gets the next free optimization index
            if (!(lvl %in% names(factor_levels_seen))) {
              factor_levels_seen[[lvl]] <- opt_par_curr
              opt_par_curr <- opt_par_curr + 1
            }
            # Add to global unconstrained index list
            pos_last <- sum(self$pl_full$unc_length[seq_len(which(names(self$par_list) == name) - 1)]) + idx_active_local[pos_in_active]
            idx_fix_active <- c(idx_fix_active, pos_last)
          }
        }
      }
      return(list(idx_active = sort(unique(idx_fix_active)), n_opt = opt_par_curr - 1))
    },

    # --- Internal helper for REML parameter classification ---
    .classify_reml_parameters = function(target_vars = NULL) {
      fix_names <- character(0)
      var_names <- character(0)
      
      for (name in names(self$par_list)) {
        is_fix_pattern <- any(sapply(private$fix_patterns, function(v) grepl(paste0("^", v, "($|\\[|\\.|_)"), name)))
        is_var_pattern <- any(sapply(private$var_patterns, function(v) grepl(paste0("^", v, "($|\\[|\\.|_)"), name)))
        
        if (is_fix_pattern && !is_var_pattern) {
          fix_names <- c(fix_names, name)
        } else if (is_var_pattern) {
          var_names <- c(var_names, name)
        } else if (!is.null(target_vars) && name %in% target_vars) {
          fix_names <- c(fix_names, name)
        } else {
          # Default to fixed if unknown
          fix_names <- c(fix_names, name)
        }
      }
      return(list(fixed = fix_names, variance = var_names))
    },

    # --- Internal helper for derived parameter calculation (delta method) ---
    .build_derived_df_table = function(func, base_out, is_generate = FALSE, se_sampling = FALSE, num_samples = 1000) {
      if (is.null(func) || is.null(base_out)) return(NULL)
      
      # This replaces the 150-line local function in optimize() and classic()
      # Integration of both logic versions
      # ... (Implementation uses logic from build_derived_df)
      return(NULL) # Placeholder for now, will implement in next chunk
    },

    # --- Internal helper for fixed parameter recursion ---
    .dispatch_fixed = function(.method_to_call, ...) {
      args <- list(...)
      fixed <- args$fixed
      args$fixed <- NULL
      new_model <- self$fixed_model(fixed)
      # Ensure the method is retrieved as a bound function from the R6 object
      func <- new_model[[.method_to_call]]
      if (!is.function(func)) stop(sprintf("Method '%s' not found in RTMB_Model.", .method_to_call))
      return(do.call(func, args))
    },

    # --- Internal helper for AD function setup ---
    .build_f_ad = function(data_local, par_list_local, log_prob_local, transform_local = NULL, jacobian_target = "all", adreport = FALSE) {
      function(y_unc_list) {
        para <- to_constrained(y_unc_list, par_list_local)

        if (!is.null(transform_local)) {
          tran_res <- transform_local(data_local, para)
          para <- c(para, tran_res)

          # transform ADREPORT (only if requested, e.g. for sdreport)
          if (adreport && length(tran_res) > 0) {
            for (n in names(tran_res)) {
              # Inject into parent environment so ADREPORT can find it by name
              assign(n, tran_res[[n]])
              eval(substitute(RTMB::ADREPORT(V), list(V = as.name(n))))
            }
          }
        }

        lp <- log_prob_local(data_local, para)

        if (jacobian_target == "all") {
          lj <- calc_log_jacobian(y_unc_list, par_list_local, only_random = FALSE)
          return(-(lp + lj))
        } else if (jacobian_target == "random") {
          lj <- calc_log_jacobian(y_unc_list, par_list_local, only_random = TRUE)
          return(-(lp + lj))
        } else {
          return(-lp)
        }
      }
    },

    # --- Logic for applying parameter fixing (fixed argument) ---
    .has_multivariate_prior_on = function(expr, target_base) {
      if (is.null(expr)) return(FALSE)

      get_base_name <- function(x) {
        if (is.name(x)) return(as.character(x))
        if (is.call(x) && identical(x[[1]], as.name("["))) {
          return(get_base_name(x[[2]]))
        }
        NULL
      }

      is_multi_dist <- function(rhs) {
        if (!is.call(rhs)) return(FALSE)
        fn <- as.character(rhs[[1]])
        length(fn) == 1 && fn %in% c("multi_normal", "multi_student_t", "multi_cauchy")
      }

      walk <- function(x) {
        if (!is.call(x)) return(FALSE)

        if (identical(x[[1]], as.name("~"))) {
          lhs_base <- get_base_name(x[[2]])
          rhs <- x[[3]]
          if (identical(lhs_base, target_base) && is_multi_dist(rhs)) {
            return(TRUE)
          }
        }

        any(vapply(as.list(x)[-1], walk, logical(1)))
      }

      walk(expr)
    },

    .apply_constraints = function(fixed = list(), silent = FALSE) {
      new_model <- self$clone()
      if (length(fixed) == 0) return(new_model)

      new_map <- as.list(new_model$map)
      new_init <- new_model$init 

      if (is.null(names(new_init))) {
        names(new_init) <- self$pl_full$names
      }

      normalize_map <- function(m) {
        if (is.null(m)) return(NULL)
        factor(as.character(m))
      }

      for (name in names(fixed)) {
        val <- fixed[[name]]
        p_base <- gsub("\\[.*\\]$", "", name)
        has_index <- grepl("\\[", name)

        if (!(p_base %in% names(self$par_list))) stop("Parameter not found: ", p_base)

        if (has_index && !is.null(self$code$model)) {
          if (private$.has_multivariate_prior_on(self$code$model, p_base)) {
            stop(
              sprintf(
                "Cannot use fixed = list('%s' = ...) because '%s' has a multivariate prior. ",
                name, p_base
              ),
              "Partial fixing of a multivariate prior is not supported. ",
              "Use a reduced model instead, e.g. remove the corresponding predictor from the formula.",
              call. = FALSE
            )
          }
        }

        p_info <- self$par_list[[p_base]]
        L_u <- p_info$unc_length

        if (is.null(new_map[[p_base]])) {
          new_map[[p_base]] <- if (L_u > 0) factor(seq_len(L_u)) else factor(integer(0))
        }
        curr_map <- new_map[[p_base]]

        start_idx <- 1
        for (n in names(self$par_list)) {
          if (n == p_base) break
          start_idx <- start_idx + self$par_list[[n]]$length
        }

        if (!grepl("\\[", name)) {
          # Fix the entire parameter
          val_vec <- if (length(val) == 1) rep(val, p_info$length) else val
          new_init[start_idx:(start_idx + p_info$length - 1)] <- as.numeric(val_vec)

          if (L_u > 0) {
            # IMPORTANT: Recreate as a factor with no levels instead of curr_map[] <- NA
            curr_map <- factor(rep(NA_character_, L_u))
          }

        } else {
          # Fix specific elements
          idx_str <- gsub(".*\\[(.*)\\].*", "\\1", name)
          p_names <- self$par_names[[p_base]]
          idx <- suppressWarnings(as.integer(idx_str))
          if (is.na(idx) && !is.null(p_names)) idx <- which(p_names == idx_str)

          if (length(idx) > 0) {
            new_init[start_idx + idx - 1] <- as.numeric(val)

            if (L_u > 0) {
              curr_map[idx] <- NA
              # Drop unused levels even in partial fixing
              curr_map <- normalize_map(curr_map)
            }
          }
        }

        new_map[[p_base]] <- curr_map
      }

      new_model$init <- new_init
      new_model$map <- new_map
      return(new_model)
    }
  )
)

