#' RTMB model object
#'
#' @description
#' An R6 class representing a Bayesian model built with RTMB.
#' This class stores model components and provides methods for
#' building the automatic differentiation object, optimizing the
#' posterior, and drawing posterior samples.
#'
#'
#' @field data Named list containing observation data.
#' @field par_list Evaluated list of parameter definitions.
#' @field log_prob Executable function for likelihood and prior calculations.
#' @field transform Function for calculating transformed parameters.
#' @field generate Function for calculating generated quantities.
#' @field par_names List of variable names corresponding to parameter dimensions.
#' @field pl_full Complete parameter list with expanded constraints and dimension information used internally.
#' @field formula Formula used for model generation (if created via a wrapper function).
#' @field requested_contrasts Character; user-requested contrast setting (e.g. "treatment").
#' @field contrasts Character; internal contrast setting used for fitting (e.g. "sum").
#' @field raw_data Data frame; the original data used for the model.
#' @field family Character string of the distribution family (if created via a wrapper function).
#' @field init List or numeric vector of initial values.
#' @field view Character vector of variable names to prioritize in summary.
#' @field code Original model AST generated by `rtmb_code()`.
#' @field map A list specifying parameter mappings for fixing values (e.g., via null_model).
#' @field prior_correction Numeric value storing the log-density of the fixed parameter for Bayes Factor correction.
#' @field type Character; the type of the model (e.g. 'lmer', 'glm', 'table', 'ttest', 'corr', 'mediation').
#' @field extra List; used to store auxiliary data (like term assignments, factors, test results) needed by methods such as classic().
#'
#' @import RTMB
RTMB_Model <- R6::R6Class(
  classname = "RTMB_Model",
  public = list(
    data = NULL,
    par_list = NULL,
    log_prob = NULL,
    transform = NULL,
    generate = NULL,
    par_names = NULL,
    pl_full = NULL,
    formula = NULL,
    raw_data = NULL,
    family = NULL,
    init = NULL,
    view = NULL,
    code = NULL,
    map = NULL,
    type = NULL,
    extra = NULL,
    contrasts = NULL,
    requested_contrasts = NULL,
    prior_correction = 0,

    # 1. Constructor
    #' @description Create a new `RTMB_Model` object.
    #' @param data Named list containing observation data.
    #' @param par_list Evaluated list of parameter definitions.
    #' @param log_prob Executable function for likelihood and prior calculations.
    #' @param transform Function for calculating transformed parameters (optional).
    #' @param generate Function for calculating generated quantities (optional).
    #' @param par_names List of variable names corresponding to parameter dimensions.
    #' @param init List or numeric vector of initial values.
    #' @param view Character vector of variable names to prioritize in summary.
    #' @param code Original model AST generated by `rtmb_code()`.
    initialize = function(data, par_list, log_prob,
                          transform = NULL, generate = NULL, par_names = NULL,
                          init = NULL, view = NULL, code = NULL) {
      self$data <- data
      self$par_names <- par_names
      self$init <- init
      self$view <- view
      self$code <- code
      self$par_list <- lapply(par_list, function(x) {
        if (typeof(x) %in% c("language", "symbol")) {
          eval(x, envir = self$data, enclos = parent.frame())
        } else {
          x
        }
      })
      self$log_prob <- log_prob
      self$transform <- transform
      self$generate <- generate

      self$pl_full <- parse_parameters(self$par_list, self$par_names)
      names(self$pl_full$init) <- self$pl_full$names

      # Changed to go through prepare_init
      init_vec <- self$prepare_init(self$init)
      self$init <- init_vec
      test_para <- constrained_vector_to_list(init_vec, self$par_list)

      test_val <- tryCatch(
        {
          if (!is.null(self$transform)) {
            test_tran <- self$transform(self$data, test_para)
            test_para <- c(test_para, test_tran)
          }
          self$log_prob(self$data, test_para)
        },
        error = function(e) {
          stop("An error occurred during the test execution of the R function (log_prob).\n[Error]: ",
            e$message,
            "\n  * Possible cause: Inappropriate initial parameter values may lead to uncomputable likelihoods (Inf or NaN).",
            "\n  * Solution: Set appropriate initial values within the domain (e.g., >0 for variance) via the 'init' argument, or reconsider the data scaling.",
            call. = FALSE
          )
        }
      )

      if (!is.numeric(test_val) || length(test_val) != 1) {
        stop("log_prob must return a single numeric value (scalar).")
      }

      if (!is.null(self$transform)) {
        test_tran <- tryCatch(
          {
            self$transform(self$data, test_para)
          },
          error = function(e) {
            stop("An error occurred during the test execution of the R function (transform).\n[Error]: ",
              e$message,
              call. = FALSE
            )
          }
        )

        if (!is.null(test_tran)) {
          if (!is.list(test_tran)) {
            stop("transform must return a list.", call. = FALSE)
          }
          if (is.null(names(test_tran)) || any(names(test_tran) == "")) {
            stop("transform must return a named list.", call. = FALSE)
          }
        }
      }

      if (!getOption("BayesRTMB.silent", FALSE)) cat("Checking RTMB setup...\n")
      test_ad <- self$build_ad_obj(init = init_vec, laplace = FALSE, jacobian_target = "all")
      test_gr <- tryCatch(test_ad$ad_obj$gr(test_ad$ad_obj$par), error = function(e) e)
      if (inherits(test_gr, "error")) {
        stop("An error occurred during gradient calculation in MakeADFun.\n[Error]: ",
          test_gr$message,
          call. = FALSE
        )
      }
    },

    # Helper method to format and complement initial values (uses self$init if no arguments are provided)
    #' @description Prepare and format initial values for the model parameters.
    #' @param init_arg Optional list or numeric vector of initial values. If NULL, defaults to `self$init` or random generation.
    #' @return A flat numeric vector of constrained initial values.
    prepare_init = function(init_arg) {
      target_init <- if (!is.null(init_arg)) init_arg else self$init

      if (is.null(target_init)) {
        return(generate_random_init(self$pl_full, self$par_list, range = 2))
      }

      # When a named list is provided (partial initial value specification)
      if (is.list(target_init)) {
        # 1. First, initialize everything with random values and convert to list format
        base_vec <- generate_random_init(self$pl_full, self$par_list, range = 2)
        base_list <- constrained_vector_to_list(base_vec, self$par_list)

        # 2. Overwrite only the parameters specified by the user
        for (name in names(target_init)) {
          if (name %in% names(base_list)) {
            base_list[[name]] <- as.numeric(target_init[[name]])
          } else {
            warning(sprintf("The initial value specified for '%s' does not exist in the model.", name), call. = FALSE)
          }
        }
        # 3. Return to a complete flat vector and return
        return(unlist(base_list, use.names = FALSE))
      }

      # When a vector is provided (full specification)
      if (is.numeric(target_init)) {
        return(target_init)
      }

      stop("init must be specified as a named list or a numeric vector.")
    },

    #' @description Get the current parameters as a named list.
    #' @param init Optional numeric vector or list of initial values. If NULL, uses the model's current initial values.
    #' @return A named list of constrained parameters.
    get_par_list = function(init = NULL) {
      init_vec <- self$prepare_init(init)
      return(constrained_vector_to_list(init_vec, self$par_list))
    },

    #' @description Get the RTMB automatic differentiation object.
    #' @param ... Arguments passed to \code{build_ad_obj}.
    #' @return A TMB objective object (ad_obj).
    get_ad_obj = function(...) {
      return(self$build_ad_obj(...)$ad_obj)
    },

    #' @description Convert a list of constrained parameters to unconstrained space.
    #' @param par_list_constrained A named list of parameters in their natural space.
    #' @return A named list of parameters in unconstrained space.
    to_unconstrained = function(par_list_constrained) {
      return(to_unconstrained_list(par_list_constrained, self$par_list))
    },

    #' @description Convert unconstrained parameters to constrained space.
    #' @param par_list_unconstrained A named list of unconstrained parameters.
    #' @return A named list of constrained parameters.
    to_constrained = function(par_list_unconstrained) {
      return(to_constrained_list(par_list_unconstrained, self$par_list))
    },

    #' @description Convert a flat unconstrained vector to a named list.
    #' @param vec Numeric vector.
    #' @return A named list.
    unconstrained_vector_to_list = function(vec) {
      return(unconstrained_vector_to_list(vec, self$par_list))
    },

    #' @description Convert a flat constrained vector to a named list.
    #' @param vec Numeric vector.
    #' @return A named list.
    constrained_vector_to_list = function(vec) {
      return(constrained_vector_to_list(vec, self$par_list))
    },

    #' @description Calculate Satterthwaite degrees of freedom.
    #' @param ad_obj RTMB AD object.
    #' @param idx_fix_active Active indices.
    #' @param L_u_total Total unconstrained length.
    #' @param opt_par Optimized parameters.
    #' @return Vector of degrees of freedom.
    calculate_satterthwaite_df = function(ad_obj, idx_fix_active = NULL, L_u_total = NULL, opt_par = NULL) {
      return(.calculate_satterthwaite_df_impl(self, ad_obj, idx_fix_active, L_u_total, opt_par))
    },

    #' @description Calculate REML Satterthwaite degrees of freedom.
    #' @param ad_obj RTMB AD object.
    #' @param opt_par Optimized parameters.
    #' @return Vector of degrees of freedom.
    calculate_reml_satterthwaite_df = function(ad_obj, opt_par, target_ran_idx) {
      return(.calculate_reml_satterthwaite_df_impl(self, ad_obj, opt_par, target_ran_idx))
    },

    #' @description Build the RTMB automatic differentiation object.
    #' @param init Optional numeric vector or list of initial values for the parameters. Default is NULL.
    #' @param laplace Logical; whether to use Laplace approximation to marginalize random effects. Default is FALSE.
    #' @param jacobian_target Character string specifying which parameters to apply Jacobian adjustments to:
    #' \itemize{
    #'   \item \code{"all"}: Apply to all parameters (standard for Bayesian MCMC).
    #'   \item \code{"random"}: Apply only to parameters with \code{random = TRUE} (standard for Laplace approximation/REML).
    #'   \item \code{"none"}: No Jacobian adjustment (standard for Maximum Likelihood estimation).
    #' }
    #' Default is "all".
    #' @param map Optional list specifying parameters to fix. Passed directly to MakeADFun. Default is NULL.
    #' @return An RTMB objective object (ad_obj).
    build_ad_obj = function(init = NULL, laplace = FALSE, jacobian_target = "all", map = NULL) {
      random_effs <- names(self$par_list)[sapply(self$par_list, function(x) isTRUE(x$random))]
      use_random <- if (laplace && length(random_effs) > 0) random_effs else NULL

      current_init <- self$prepare_init(init)
      current_init_list <- constrained_vector_to_list(current_init, self$par_list)
      init_unc_list <- to_unconstrained(current_init_list, self$par_list)

      pl_full_local <- self$pl_full
      par_list_local <- self$par_list
      log_prob_local <- self$log_prob
      data_local <- self$data

      f_ad <- function(y_unc_list) {
        para <- to_constrained(y_unc_list, par_list_local)

        if (!is.null(self$transform)) {
          tran_res <- self$transform(data_local, para)
          para <- c(para, tran_res)

          # transform ADREPORT
          if (length(tran_res) > 0) {
            for (n in names(tran_res)) {
              assign(n, tran_res[[n]])
              eval(substitute(RTMB::ADREPORT(V), list(V = as.name(n))))
            }
          }
        }

        lp <- log_prob_local(data_local, para)

        if (jacobian_target == "all") {
          lj <- calc_log_jacobian(y_unc_list, par_list_local, only_random = FALSE)
          return(-(lp + lj))
        } else if (jacobian_target == "random") {
          lj <- calc_log_jacobian(y_unc_list, par_list_local, only_random = TRUE)
          return(-(lp + lj))
        } else {
          return(-lp)
        }
      }

      ad_obj <- tryCatch(
        {
          RTMB::MakeADFun(
            func = f_ad,
            parameters = init_unc_list,
            random = use_random,
            map = if (is.null(map)) self$map else utils::modifyList(as.list(self$map), as.list(map)),
            silent = TRUE
          )
        },
        error = function(e) {
          stop("Failed to setup MakeADFun.\n[Error]: ", e$message, call. = FALSE)
        }
      )

      return(list(
        ad_obj = ad_obj,
        pl_full = pl_full_local,
        use_random = use_random
      ))
    },

    # 3. Maximum Likelihood / MAP Estimation Method
    #' @param laplace Logical; whether to use Laplace approximation. Default is TRUE.
    #' @param init Optional initial values for parameters.
    #' @param num_estimate Integer; Number of multi-start optimization runs. Default is 1.
    #' @param control A list of control settings passed to the optimizer.
    #' @param optimizer Character; The optimizer to use, either "optim" or "nlminb". Default is "nlminb".
    #' @param method Character; The method for "optim" (e.g. "BFGS", "L-BFGS-B"). Default is "BFGS".
    #' @param map Optional list specifying parameters to fix. Default is NULL.
    #' @param se Logical; whether to estimate standard errors and confidence intervals. Default is TRUE.
    #' @param ci_method Character; The method for CI estimation: "wald" (Wald CI) or "sampling" (Simulation-based). Default is "wald". Note: Profile Likelihood is now available via the `$profile()` method of the returned fit object.
    #' @param se_method Alias for `ci_method` (for backward compatibility).
    #' @param se_sampling Logical; Alias for `ci_method = "sampling"` (for backward compatibility).
    #' @param num_samples Integer; number of samples to draw when se_method is "sampling". Default is 1000.
    #' @param seed Integer; random seed for sampling.
    #' @param df Degrees of freedom for the t-distribution used in confidence intervals and summary.
    #' Can be a numeric value, NULL (for Inf/Normal), or "auto" for automatic Satterthwaite approximation. Default is NULL.
    #' @param fixed Optional list specifying parameter values to fix.
    #' @param REML Logical; whether to use Restricted Maximum Likelihood (REML). Default is FALSE.
    #' @param df_pars Character vector of parameters to be treated as fixed effects for REML/DF calculation, or "auto". Default is "auto".
    #' @return A fitted `MAP_Fit` object.
    optimize = function(laplace = TRUE, init = NULL, num_estimate = 1, control = list(),
                        optimizer = "nlminb", method = "BFGS", map = NULL,
                        se = TRUE, ci_method = c("wald", "sampling"),
                        se_method = NULL, se_sampling = FALSE, num_samples = 1000, seed = 123,
                        df = NULL, fixed = NULL, REML = FALSE, df_pars = "auto") {
      if (!is.null(fixed)) {
        return(self$fixed_model(fixed)$optimize(
          laplace = laplace, init = init, num_estimate = num_estimate, control = control,
          optimizer = optimizer, method = method, map = map, se = se,
          ci_method = ci_method, se_method = se_method, se_sampling = se_sampling,
          num_samples = num_samples, seed = seed, df = df, REML = REML, df_pars = df_pars
        ))
      }

      if (!is.null(se_method)) ci_method <- se_method
      ci_method <- match.arg(ci_method)
      if (isTRUE(se_sampling) && ci_method == "wald") ci_method <- "sampling" # Backward compatibility
      if (ci_method == "sampling") se_sampling <- TRUE
      cat("Starting optimization...\n")

      if (is.null(df)) df <- Inf
      auto_df <- identical(df, "auto")
      df_t <- if (is.numeric(df)) df else Inf

      opt_results <- list()
      obj_vals <- numeric(num_estimate)
      conv_codes <- numeric(num_estimate)

      # --- 1. Determine target variables for DF calculation ---
      if (identical(df_pars, "auto")) {
        if (!is.null(self$extra$df_pars)) {
          target_vars <- self$extra$df_pars
        } else {
          # Default to standard fixed effect names if no specific df_pars are provided
          target_vars <- c("Intercept", "Intercept_c", "b", "mean", "prob", "beta", "mu", "delta", "diff", "mean_diff")
        }
      } else if (identical(df_pars, "none")) {
        target_vars <- character(0)
      } else if (identical(df_pars, "all")) {
        target_vars <- names(self$par_list)
      } else {
        target_vars <- df_pars
      }

      # --- 2. Variable Classification for REML ---
      original_par_list <- self$par_list
      if (REML) {
        # Use centralized classification logic
        reml_info <- private$.classify_reml_parameters(target_vars)
        fix_names <- reml_info$fixed
        
        modified_par_list <- self$par_list
        for (name in names(modified_par_list)) {
          is_ran_original <- isTRUE(modified_par_list[[name]]$random)
          if (name %in% fix_names || is_ran_original) {
            modified_par_list[[name]]$random <- TRUE
          } else {
            modified_par_list[[name]]$random <- FALSE
          }
        }
        self$par_list <- modified_par_list
        on.exit(
          {
            self$par_list <- original_par_list
          },
          add = TRUE
        )
        laplace <- TRUE
      }

      # Jacobian is not required for MAP estimation
      jac_target <- if (laplace) "random" else "none"

      ad_setup <- self$build_ad_obj(init = init, laplace = laplace, jacobian_target = jac_target, map = map)
      base_ad_obj <- ad_setup$ad_obj

      for (i in 1:num_estimate) {
        if (num_estimate > 1) {
          cat(sprintf("Optimization run %d/%d...\r", i, num_estimate))
        }

        res <- tryCatch(
          {
            if (i > 1 && is.null(init)) {
              base_ad_obj$par <- base_ad_obj$par + rnorm(length(base_ad_obj$par), mean = 0, sd = 0.5)
            }

            if (length(base_ad_obj$par) == 0) {
              # No parameters to optimize (all fixed and/or random effects integrated out)
              cat("No fixed effects to optimize. Returning initial values.\n")
              opt <- list(
                par = numeric(0),
                objective = base_ad_obj$fn(numeric(0)),
                convergence = 0,
                message = "all parameters fixed",
                iterations = 0,
                evaluations = c(obj = 1, grad = 0)
              )
            } else if (optimizer == "nlminb") {
              if (is.null(control$iter.max)) control$iter.max <- 5000
              if (is.null(control$eval.max)) control$eval.max <- 5000
              if (is.null(control$rel.tol)) control$rel.tol <- 1e-8

              opt <- suppressWarnings(nlminb(
                start     = base_ad_obj$par,
                objective = base_ad_obj$fn,
                gradient  = base_ad_obj$gr,
                control   = control
              ))
            } else if (optimizer == "optim") {
              if (is.null(control$maxit)) control$maxit <- 5000

              opt <- optim(
                par     = base_ad_obj$par,
                fn      = base_ad_obj$fn,
                gr      = base_ad_obj$gr,
                method  = method,
                control = control
              )
              opt$objective <- opt$value
            } else {
              stop("optimizer must be either 'optim' or 'nlminb'.")
            }

            list(opt = opt, ad_obj = base_ad_obj)
          },
          error = function(e) {
            warning("Optimization error: ", e$message, call. = FALSE)
            NULL
          }
        )

        if (!is.null(res)) {
          opt_results[[i]] <- res
          obj_vals[i] <- res$opt$objective
          conv_codes[i] <- res$opt$convergence
        } else {
          opt_results[[i]] <- NULL
          obj_vals[i] <- NA
          conv_codes[i] <- NA
        }
      }
      cat("\n")

      valid_idx <- which(!is.na(obj_vals))
      if (length(valid_idx) == 0) {
        stop("All optimization attempts failed. Check the initial values and model definition.")
      }

      best_idx <- valid_idx[which.min(obj_vals[valid_idx])]
      best_res <- opt_results[[best_idx]]

      if (num_estimate == 1) {
        status <- if (conv_codes[1] == 0) "converged" else "Not Converged"
        cat(sprintf("Optimization %s. Final objective: %.2f\n", status, obj_vals[1]))
      } else {
        cat("\nOptimization Diagnostics per estimate:\n")
        for (i in 1:num_estimate) {
          if (is.na(obj_vals[i])) {
            status_str <- "Failed"
          } else {
            status_str <- if (conv_codes[i] == 0) "Converged" else "Not Converged"
          }
          best_marker <- if (i == best_idx) "  <-- BEST" else ""
          cat(sprintf(
            "  est%d: Objective = %10.2f, Code = %s (%s)%s\n",
            i, obj_vals[i], as.character(conv_codes[i]), status_str, best_marker
          ))
        }
        cat("\n")
      }

      ad_obj <- best_res$ad_obj
      opt <- best_res$opt
      ad_obj$fn(opt$par)

      sd_rep <- if (se) tryCatch(RTMB::sdreport(ad_obj), warning = function(w) NULL, error = function(e) NULL) else NULL

      unc_est_vec <- unlist(ad_obj$env$parList(), use.names = FALSE)

      # --- Core correction: Accurate mapping between opt$par and last.par ---
      L_u_total <- length(unc_est_vec)
      idx_ran <- ad_obj$env$random
      if (is.null(idx_ran)) idx_ran <- integer(0)

      target_map <- if (!is.null(map)) map else self$map

      # Construct accurate indices of 'active fixed parameters' estimated by TMB
      active_info <- private$.compute_active_indices(target_map)
      idx_fix_active <- active_info$idx_active

      # Profile Likelihood CI calculation is now moved to $profile() method of MAP_Fit

      # --- Use optimization results for point estimates to prevent sdreport's Delta method bias ---
      unc_est_vec[idx_fix_active] <- opt$par

      # For random effects, update with the latest posterior modes from sdreport if available
      if (laplace && !is.null(sd_rep) && length(idx_ran) > 0) {
        smry_ran <- tryCatch(summary(sd_rep, select = "random"), warning = function(w) NULL, error = function(e) NULL)
        if (!is.null(smry_ran) && nrow(smry_ran) == length(idx_ran)) {
          unc_est_vec[idx_ran] <- smry_ran[, "Estimate"]
        }
      }

      unc_se_vec <- rep(0, L_u_total)
      Cov_u <- diag(0, nrow = L_u_total, ncol = L_u_total)
      fallback_needed <- FALSE
      cov_source <- "none"

      if (!is.null(sd_rep) && !is.null(sd_rep$cov.fixed)) {
        # Extract standard errors directly from the diagonal of the cov.fixed matrix without using summary
        se_fix <- sqrt(pmax(diag(sd_rep$cov.fixed), 0))
        if (!isTRUE(sd_rep$pdHess) || any(is.na(se_fix)) || any(is.nan(se_fix))) {
          fallback_needed <- TRUE
          cat("Warning: sdreport produced NAs or non-positive-definite Hessian. Falling back to ginv().\n")
        }
        # Safety check: Ensure the number of calculated indices perfectly matches the TMB output size
        if (length(idx_fix_active) == length(se_fix)) {
          # 1. Assign standard errors to independent parameters
          unc_se_vec[idx_fix_active] <- se_fix

          # 2. Assign to the corresponding locations in the covariance matrix
          Cov_u[idx_fix_active, idx_fix_active] <- sd_rep$cov.fixed
          cov_source <- "sdreport"

          # 3. Copy standard errors to shared (duplicate) parameters
          idx_curr <- 1
          for (name in names(self$par_list)) {
            L_u <- self$par_list[[name]]$unc_length
            if (L_u > 0) {
              map_f <- if (!is.null(target_map[[name]])) target_map[[name]] else NULL
              for (i in 1:L_u) {
                pos_last <- idx_curr + i - 1
                if (pos_last %in% idx_ran) next
                if (!is.null(map_f) && !is.na(map_f[i])) {
                  lvl <- as.character(map_f[i])
                  mapped_opt_idx <- which(idx_fix_active == pos_last) # simplified for shared mapping
                  if (length(mapped_opt_idx) > 0) {
                     # Re-use already computed se from index
                  }
                }
              }
              idx_curr <- idx_curr + L_u
            }
          }

          # Get standard errors of random effects
          if (laplace && length(idx_ran) > 0) {
            smry_ran <- tryCatch(summary(sd_rep, select = "random"), warning = function(w) NULL, error = function(e) NULL)
            if (!is.null(smry_ran) && nrow(smry_ran) == length(idx_ran)) {
              unc_se_vec[idx_ran] <- smry_ran[, "Std. Error"]
            }
          }
        } else {
          fallback_needed <- TRUE
          cat("Warning: Computed active parameter indices mismatch TMB output. Falling back to ginv().\n")
        }
      } else {
        fallback_needed <- TRUE
      }

      if (se && fallback_needed) {
        cat("sdreport failed or produced NAs. Falling back to ginv()...\n")
        eps_jitter <- 1e-6
        H <- tryCatch(ad_obj$he(opt$par + eps_jitter), warning = function(w) NULL, error = function(e) NULL)
        if (is.null(H) || any(is.na(H) | is.nan(H))) {
          H <- tryCatch(ad_obj$he(opt$par - eps_jitter), warning = function(w) NULL, error = function(e) NULL)
        }
        if (!is.null(H)) {
          H[!is.finite(H)] <- 0
          diag(H) <- diag(H) + 1e-6
          if (!requireNamespace("MASS", quietly = TRUE)) {
            warning("Package 'MASS' is required for ginv(). Standard errors will be NA.")
          } else {
            Cov_pseudo <- tryCatch(MASS::ginv(H), warning = function(w) NULL, error = function(e) NULL)
            if (!is.null(Cov_pseudo)) {
              se_pseudo <- sqrt(pmax(diag(Cov_pseudo), 0))

              if (length(idx_fix_active) == length(se_pseudo)) {
                unc_se_vec[idx_fix_active] <- se_pseudo
                Cov_u[idx_fix_active, idx_fix_active] <- Cov_pseudo
                cov_source <- "fallback"
              }
            } else {
              cat("ginv() calculation also failed.\n")
            }
          }
        } else {
          cat("Hessian calculation failed even after adding jitter.\n")
        }
      }

      unc_est_list <- unconstrained_vector_to_list(unc_est_vec, self$par_list)
      unc_se_list <- unconstrained_vector_to_list(unc_se_vec, self$par_list)
      con_est_list <- to_constrained(unc_est_list, self$par_list)

      # Fill diagonal for parameters without covariance information while preserving any
      # covariance matrix obtained from sdreport() or the fallback ginv() route.
      diag(Cov_u) <- pmax(diag(Cov_u), unc_se_vec^2)
      Cov_u[is.na(Cov_u)] <- 0

      con_se_list <- list()
      con_lower_list <- list()
      con_upper_list <- list()

      samps_con <- list()
      samps_tran <- list()
      samps_gq <- list()

      # --- Degrees of freedom adjustment ---
      if (any(!is.infinite(df_t))) {
        est_dfs_all <- rep(df_t[1], L_u_total)
      } else if (auto_df || REML) {
        # (A) Active parameters (ML side)
        est_dfs_all <- self$calculate_satterthwaite_df(ad_obj, idx_fix_active, L_u_total, opt$par)

        # (B) Integrated-out parameters (REML side)
        if (REML && length(ad_obj$env$random) > 0) {
          full_par_names <- names(ad_obj$env$last.par)
          target_full_idx <- which(full_par_names %in% target_vars | 
                                   gsub("\\[.*\\]$", "", full_par_names) %in% target_vars)
          idx_ran <- ad_obj$env$random
          target_ran_idx <- match(target_full_idx, idx_ran)

          valid_mask <- !is.na(target_ran_idx)
          target_ran_idx <- target_ran_idx[valid_mask]
          valid_full_idx <- target_full_idx[valid_mask]

          if (length(target_ran_idx) > 0) {
            reml_dfs <- self$calculate_reml_satterthwaite_df(ad_obj, opt$par, target_ran_idx)
            est_dfs_all[valid_full_idx] <- if (is.list(reml_dfs)) reml_dfs$df else reml_dfs
          }
        }
        ad_obj$fn(opt$par)
      } else {
        est_dfs_all <- rep(Inf, L_u_total)
      }

      # --- SE Sampling Logic ---
      if (se_sampling) {
        cat(sprintf("Using simulation-based error propagation (%d samples)...\n", num_samples))
        set.seed(seed)
        if (!requireNamespace("MASS", quietly = TRUE)) {
          stop("Package 'MASS' is required for se_sampling=TRUE.")
        }

        Cov_u_valid <- Cov_u[idx_fix_active, idx_fix_active, drop = FALSE]
        mu_valid <- unc_est_vec[idx_fix_active]

        Cov_u_valid[!is.finite(Cov_u_valid)] <- 0
        mu_valid[!is.finite(mu_valid)] <- 0

        # Ensure Positive Definite for MASS::mvrnorm
        eig <- eigen(Cov_u_valid, symmetric = TRUE)
        eig$values <- pmax(eig$values, 1e-8)
        Cov_u_pd <- eig$vectors %*% diag(eig$values, nrow = length(eig$values)) %*% t(eig$vectors)

        raw_samples <- MASS::mvrnorm(num_samples, mu = mu_valid, Sigma = Cov_u_pd)
        if (!is.matrix(raw_samples)) raw_samples <- as.matrix(raw_samples)

        # --- Multivariate t-distribution (or Satterthwaite) scaling ---
        active_dfs <- est_dfs_all[idx_fix_active]

        # Transform Normal samples to t-samples while preserving the correlation structure
        # Formula: t = mu + (z * sigma) * sqrt(df / chisq(df))
        for (j in 1:ncol(raw_samples)) {
          df_j <- active_dfs[j]
          if (!is.na(df_j) && !is.infinite(df_j)) {
            sigma_j <- sqrt(Cov_u_pd[j, j])
            # Standardized z-scores from MVN
            z <- (raw_samples[, j] - mu_valid[j]) / (sigma_j + 1e-12)
            # Sample chi-square factors for this parameter
            w <- rchisq(num_samples, df = df_j)
            # Rescale to match t-distribution marginals
            raw_samples[, j] <- mu_valid[j] + z * sigma_j * sqrt(df_j / pmax(w, 1e-6))
          }
        }

        u_samples_mat <- matrix(rep(unc_est_vec, each = num_samples), nrow = num_samples)
        u_samples_mat[, idx_fix_active] <- raw_samples

        # Sample random effects independently
        if (laplace && length(idx_ran) > 0) {
          for (ridx in idx_ran) {
            u_samples_mat[, ridx] <- rnorm(num_samples, mean = unc_est_vec[ridx], sd = unc_se_vec[ridx])
          }
        }

        local_data <- self$data
        local_par_list <- self$par_list
        local_transform <- self$transform
        local_generate <- self$generate

        test_con_list <- to_constrained(unconstrained_vector_to_list(unc_est_vec, local_par_list), local_par_list)

        for (name in names(test_con_list)) {
          samps_con[[name]] <- matrix(NA_real_, nrow = num_samples, ncol = length(as.numeric(test_con_list[[name]])))
        }

        if (!is.null(local_transform)) {
          test_tran <- local_transform(local_data, test_con_list)
          if (!is.null(test_tran)) {
            for (name in names(test_tran)) {
              samps_tran[[name]] <- matrix(NA_real_, nrow = num_samples, ncol = length(as.numeric(test_tran[[name]])))
            }
            test_con_list <- c(test_con_list, test_tran)
          }
        }

        if (!is.null(local_generate)) {
          test_gq <- local_generate(local_data, test_con_list)
          if (!is.null(test_gq)) {
            for (name in names(test_gq)) {
              samps_gq[[name]] <- matrix(NA_real_, nrow = num_samples, ncol = length(as.numeric(test_gq[[name]])))
            }
          }
        }

        process_sample <- function(s, u_vec) {
          tmp_unc_list <- unconstrained_vector_to_list(u_vec, local_par_list)
          tmp_con_list <- to_constrained(tmp_unc_list, local_par_list)

          for (name in names(tmp_con_list)) {
            samps_con[[name]][s, ] <<- as.numeric(tmp_con_list[[name]])
          }

          if (!is.null(local_transform)) {
            tmp_tran <- local_transform(local_data, tmp_con_list)
            if (!is.null(tmp_tran)) {
              for (name in names(tmp_tran)) {
                samps_tran[[name]][s, ] <<- as.numeric(tmp_tran[[name]])
              }
              tmp_con_list <- c(tmp_con_list, tmp_tran)
            }
          }

          if (!is.null(local_generate)) {
            tmp_gq <- local_generate(local_data, tmp_con_list)
            if (!is.null(tmp_gq)) {
              for (name in names(tmp_gq)) {
                samps_gq[[name]][s, ] <<- as.numeric(tmp_gq[[name]])
              }
            }
          }
        }

        # Progress reporting for transformation
        if (requireNamespace("progressr", quietly = TRUE)) {
          progressr::with_progress({
            p <- progressr::progressor(steps = num_samples)

            update_interval <- max(1, floor(num_samples / 100))

            for (s in 1:num_samples) {
              process_sample(s, u_samples_mat[s, ])
              if (s %% update_interval == 0) {
                p(amount = update_interval)
              }
            }
            remainder <- num_samples %% update_interval
            if (remainder != 0) {
              p(amount = remainder)
            }
          })
        } else {
          for (s in 1:num_samples) {
            process_sample(s, u_samples_mat[s, ])
          }
        }

        # Compute SE and CI
        for (name in names(self$par_list)) {
          p_info <- self$par_list[[name]]
          mat <- samps_con[[name]]

          if (is.null(mat)) {
            c_se <- rep(NA, p_info$length)
            c_low <- rep(NA, p_info$length)
            c_up <- rep(NA, p_info$length)
          } else {
            c_se <- apply(mat, 2, sd, na.rm = TRUE)
            c_low <- apply(mat, 2, quantile, probs = 0.025, na.rm = TRUE)
            c_up <- apply(mat, 2, quantile, probs = 0.975, na.rm = TRUE)
          }

          if (length(p_info$dim) > 1) {
            dim(c_se) <- p_info$dim
            dim(c_low) <- p_info$dim
            dim(c_up) <- p_info$dim
          }
          con_se_list[[name]] <- c_se
          con_lower_list[[name]] <- c_low
          con_upper_list[[name]] <- c_up
        }
      } else {
        # Standard SE calculation (Wald)
        eps_diff <- 1e-5
        u_idx_current <- 1

        for (name in names(self$par_list)) {
          p_info <- self$par_list[[name]]
          u_val <- unc_est_list[[name]]
          u_se <- unc_se_list[[name]]
          c_val <- con_est_list[[name]]

          L_u <- p_info$unc_length
          L_c <- p_info$length

          if (L_u > 0) {
            u_indices <- u_idx_current:(u_idx_current + L_u - 1)
            u_idx_current <- u_idx_current + L_u
          } else {
            u_indices <- integer(0)
          }

          transform_single <- function(u) {
            tmp_list <- unc_est_list
            tmp_list[[name]] <- u
            tmp_con <- to_constrained(tmp_list, self$par_list)
            return(as.numeric(tmp_con[[name]]))
          }

          J <- matrix(0, nrow = L_c, ncol = L_u)
          for (i in seq_len(L_u)) {
            u_tmp <- u_val
            u_tmp[i] <- u_tmp[i] + eps_diff
            c_tmp <- transform_single(u_tmp)
            J[, i] <- (c_tmp - as.numeric(c_val)) / eps_diff
          }

          c_se <- numeric(L_c)
          if (L_u > 0) {
            Cov_sub <- Cov_u[u_indices, u_indices, drop = FALSE]
            for (j in 1:L_c) {
              c_se[j] <- sqrt(sum((J[j, ] %*% Cov_sub) * J[j, ], na.rm = TRUE))
            }
          }

          if (length(p_info$dim) > 1) dim(c_se) <- p_info$dim
          con_se_list[[name]] <- c_se

          if (p_info$bounds == "corr_matrix" || p_info$type == "corr_matrix") {
            # Fisher z-transform based CIs for correlation matrix elements
            # z = atanh(rho), SE(z) = SE(rho) / (1 - rho^2)
            rho_val <- as.numeric(c_val)
            # Clip rho to avoid Inf in atanh
            rho_clipped <- pmax(pmin(rho_val, 0.9999), -0.9999)
            z_val <- atanh(rho_clipped)
            z_se <- c_se / (1 - rho_clipped^2 + 1e-10)
            
            u_dfs <- est_dfs_all[u_indices]
            u_q_95 <- if (any(is.na(u_dfs) | is.infinite(u_dfs))) qnorm(0.975) else qt(0.975, df = pmax(mean(u_dfs, na.rm = TRUE), 2.1))
            
            z_low <- z_val - u_q_95 * z_se
            z_up <- z_val + u_q_95 * z_se
            c_low <- tanh(z_low)
            c_up <- tanh(z_up)
            
            # Handle diagonals (fixed at 1.0)
            is_fixed <- c_se < 1e-10 & abs(rho_val - 1) < 1e-8
            if (any(is_fixed)) {
              c_low[is_fixed] <- 1.0
              c_up[is_fixed] <- 1.0
            }
          } else {
            u_dfs <- est_dfs_all[u_indices]
            u_q_95 <- ifelse(is.na(u_dfs) | is.infinite(u_dfs), qnorm(0.975), qt(0.975, df = pmax(u_dfs, 2.1)))
            u_low <- u_val - u_q_95 * u_se
            u_up <- u_val + u_q_95 * u_se
            c_low <- transform_single(u_low)
            c_up <- transform_single(u_up)

            c_low_final <- pmin(c_low, c_up)
            c_up_final <- pmax(c_low, c_up)
            c_low <- c_low_final
            c_up <- c_up_final
          }

          if (length(p_info$dim) > 1) {
            dim(c_low) <- p_info$dim
            dim(c_up) <- p_info$dim
          }
          con_lower_list[[name]] <- c_low
          con_upper_list[[name]] <- c_up
        }
      }

      # Restore original par_list before result categorization
      if (REML) self$par_list <- original_par_list

      # Map unconstrained DFs back to parameter list structure
      df_list_con <- list()
      # Determine if we should include DF in the output
      show_df <- auto_df || REML || !is.infinite(df_t)

      if (exists("est_dfs_all")) {
        # est_dfs_all is on unconstrained scale. For summary, we map it to constrained parameters.
        # For most cases (regression coeffs), 1:1 mapping is fine.
        # For complex constraints, we provide DFs where lengths match.
        df_list_unc <- unconstrained_vector_to_list(est_dfs_all, self$par_list)
        for (name in names(self$par_list)) {
          p <- self$par_list[[name]]
          if (p$unc_length == p$length) {
            df_list_con[[name]] <- df_list_unc[[name]]
          } else {
            # For complex types, we fill with NA or Inf as the mapping is not 1:1
            df_list_con[[name]] <- rep(Inf, p$length)
          }
        }
      }

      # Compile output format
      build_df <- function(target_random = FALSE) {
        names_vec <- c()
        est_vec <- c()
        se_vec <- c()
        low_vec <- c()
        up_vec <- c()
        df_vec <- c()

        for (name in names(self$par_list)) {
          p_info <- self$par_list[[name]]
          if (p_info$random == target_random) {
            names_def <- self$par_names[[name]]
            f_names <- generate_flat_names(name, p_info$dim, names_def)

            names_vec <- c(names_vec, f_names)
            est_vec <- c(est_vec, as.numeric(con_est_list[[name]]))
            se_vec <- c(se_vec, as.numeric(con_se_list[[name]]))
            low_vec <- c(low_vec, as.numeric(con_lower_list[[name]]))
            up_vec <- c(up_vec, as.numeric(con_upper_list[[name]]))
            if (!is.null(df_list_con[[name]])) {
              df_vec <- c(df_vec, as.numeric(df_list_con[[name]]))
            } else {
              df_vec <- c(df_vec, rep(Inf, p_info$length))
            }
          }
        }

        if (length(names_vec) == 0) {
          return(NULL)
        }

        res_df <- data.frame(
          Estimate     = est_vec,
          `Std. Error` = se_vec,
          `Lower 95%`  = low_vec,
          `Upper 95%`  = up_vec,
          check.names  = FALSE
        )
        if (show_df) {
          res_df$DF <- df_vec
        }
        rownames(res_df) <- names_vec
        return(res_df)
      }

      df_fixed <- build_df(target_random = FALSE)
      df_random <- if (laplace) build_df(target_random = TRUE) else NULL

      con_est_vec <- unlist(con_est_list, use.names = FALSE)

      tran_list <- NULL
      if (!is.null(self$transform)) {
        tran_list <- tryCatch(self$transform(self$data, con_est_list), warning = function(w) NULL, error = function(e) NULL)
      }

      gq_list <- NULL
      if (!is.null(self$generate)) {
        tmp_con_list <- con_est_list
        if (!is.null(tran_list)) tmp_con_list <- c(tmp_con_list, tran_list)
        gq_list <- tryCatch(self$generate(self$data, tmp_con_list), warning = function(w) NULL, error = function(e) NULL)
      }

      # Use centralized derived DF table logic
      df_transform <- private$.build_derived_df_table(self$transform, tran_list, is_generate = FALSE, se_sampling = se_sampling, num_samples = num_samples, sd_rep = sd_rep)
      df_generate <- private$.build_derived_df_table(self$generate, gq_list, is_generate = TRUE, se_sampling = se_sampling, num_samples = num_samples, sd_rep = sd_rep)

      log_ml <- NA
      if (!is.null(sd_rep) && !is.null(sd_rep$cov.fixed) && !fallback_needed) {
        D <- length(opt$par)
        cov_mat <- sd_rep$cov.fixed
        eig <- tryCatch(eigen(cov_mat, symmetric = TRUE), warning = function(w) NULL, error = function(e) NULL)

        if (!is.null(eig)) {
          vals <- eig$values
          if (any(vals <= 1e-8)) {
            cat("Hessian is singular or not positive definite. Marginal likelihood (Laplace) is not reliable and set to NA.\n")
          } else {
            if (laplace) {
              lj_all <- calc_log_jacobian(unc_est_list, self$par_list, only_random = FALSE)
              lj_ran <- calc_log_jacobian(unc_est_list, self$par_list, only_random = TRUE)
              lj_missing <- lj_all - lj_ran
            } else {
              lj_missing <- calc_log_jacobian(unc_est_list, self$par_list, only_random = FALSE)
            }

            log_det_cov <- sum(log(vals))
            log_ml <- -opt$objective + lj_missing + (D / 2) * log(2 * pi) + 0.5 * log_det_cov - self$prior_correction
          }
        }
      }

      opt_history <- data.frame(estimate = 1:num_estimate, objective = obj_vals, code = conv_codes)

      res_obj <- MAP_Fit$new(
        model          = self,
        par_vec        = con_est_vec,
        par            = con_est_list,
        objective      = opt$objective,
        log_ml         = log_ml,
        convergence    = opt$convergence,
        sd_rep         = sd_rep,
        df_fixed       = df_fixed,
        random_effects = df_random,
        df_transform   = df_transform,
        df_generate    = df_generate,
        opt_history    = opt_history,
        transform      = tran_list,
        generate       = gq_list,
        se_samples     = if (se_sampling) list(con = samps_con, tran = samps_tran, gq = samps_gq) else NULL,
        par_unc        = unc_est_vec,
        ci_method      = ci_method,
        laplace        = laplace,
        map            = target_map,
        vcov_unc       = Cov_u
      )

      return(res_obj)
    },

    # 3.5. Classic Frequentist Inference Method
    #' @description Perform frequentist inference (REML/ML) with automatic Satterthwaite degrees of freedom.
    #' @param df "auto" for Satterthwaite, numeric/Inf for specific degrees of freedom.
    #' @param df_pars Character vector of parameters to estimate degrees of freedom for (or "auto" / "all" / "none"). Default is "auto".
    #' @param REML Logical; whether to use Restricted Maximum Likelihood. Default is TRUE.
    #' @param view Character vector of parameters to prioritize in the summary output.
    #' @param views Alias for \code{view}.
    #' @param map Optional list specifying parameters to fix (factors).
    #' @param fixed Optional list specifying parameter values to fix.
    #' @return A `Classic_Fit` object.
    classic = function(df = "auto", df_pars = "auto", REML = TRUE, view = NULL, views = NULL, map = NULL, fixed = NULL) {
      if (!is.null(fixed)) {
        return(self$fixed_model(fixed)$classic(
          df = df, df_pars = df_pars, REML = REML, view = view, views = views, map = map
        ))
      }
      if (is.null(view) && !is.null(views)) view <- views

      # --- 1. Determine target variables for DF calculation ---
      if (identical(df_pars, "auto")) {
        if (!is.null(self$extra$df_pars)) {
          target_vars <- self$extra$df_pars
        } else {
          # Default patterns for fixed effects
          fix_vars_default <- c("Intercept", "Intercept_c", "b", "mean", "prob", "beta", "mu", "delta", "diff", "mean_diff")
          target_vars <- names(self$par_list)[sapply(names(self$par_list), function(n) {
            p_info <- self$par_list[[n]]
            is_fixed_name <- any(sapply(fix_vars_default, function(v) grepl(paste0("^", v, "($|\\[|\\.|_)"), n)))
            is_unbounded <- identical(p_info$bounds, "none")

            # Target if it's a known fixed name OR if it has no bounds (and is not already marked as random)
            (is_fixed_name || is_unbounded) && !isTRUE(p_info$random)
          })]
        }
      } else if (identical(df_pars, "none")) {
        target_vars <- character(0)
      } else if (identical(df_pars, "all")) {
        target_vars <- names(self$par_list)
      } else {
        target_vars <- df_pars
      }

      # --- 2. Variable Classification for REML/ML Pipeline ---
      modified_par_list <- self$par_list
      if (REML) {
        reml_info <- private$.classify_reml_parameters(target_vars)
        fix_names <- reml_info$fixed
        for (name in names(modified_par_list)) {
          is_ran_original <- isTRUE(modified_par_list[[name]]$random)
          if (name %in% fix_names || is_ran_original) {
            modified_par_list[[name]]$random <- TRUE
          } else {
            modified_par_list[[name]]$random <- FALSE
          }
        }
      } else {
        for (name in names(modified_par_list)) {
          modified_par_list[[name]]$random <- isTRUE(modified_par_list[[name]]$random)
        }
      }

      # --- 3. Additional test results and diagnostics ---
      test_results <- list()
      if (!is.null(self$data$prior$type) && self$data$prior$type != "uniform") {
        warning("Prior distributions are specified. The results are based on Regularized Maximum Likelihood and should be interpreted with caution.", call. = FALSE)
      }

      if (!is.null(self$type)) {
        if (self$type == "table") {
          tab <- self$extra$tab
          test_results$chisq <- stats::chisq.test(tab, correct = isTRUE(self$extra$correct))
          test_results$fisher <- try(stats::fisher.test(tab), silent = TRUE)
        }
      }

      original_par_list <- self$par_list
      self$par_list <- modified_par_list
      on.exit(
        {
          self$par_list <- original_par_list
        },
        add = TRUE
      )

      laplace_flag <- REML || any(sapply(modified_par_list, function(x) isTRUE(x$random)))

      ad_setup <- tryCatch(self$build_ad_obj(laplace = laplace_flag, jacobian_target = "none"),
        error = function(e) stop("MakeADFun failed: ", e$message)
      )
      ad_obj <- ad_setup$ad_obj

      if (length(ad_obj$par) > 0) {
        opt <- tryCatch(suppressWarnings(nlminb(start = ad_obj$par, objective = ad_obj$fn, gradient = ad_obj$gr)),
          error = function(e) stop("Optimization failed: ", e$message)
        )
      } else {
        opt <- list(par = numeric(0), objective = ad_obj$fn(numeric(0)), convergence = 0)
      }

      L_u_total <- length(ad_obj$env$last.par)
      est_dfs_all <- rep(if (is.numeric(df)) df[1] else Inf, L_u_total)

      if (identical(df, "auto") && length(target_vars) > 0) {
        # (A) ML 等で最適化対象となる固定効果の DF
        idx_fix_active <- ad_obj$env$lfixed()
        est_dfs_all <- self$calculate_satterthwaite_df(ad_obj, idx_fix_active, L_u_total, opt$par)

        # (B) REML 等でランダム効果と共に積分消去された固定効果の DF
        if (length(ad_obj$env$random) > 0) {
          full_par_names <- names(ad_obj$env$last.par)
          target_full_idx <- which(full_par_names %in% target_vars | 
                                   gsub("\\[.*\\]$", "", full_par_names) %in% target_vars)

          # ランダム効果ベクトルに対する相対インデックスに変換
          idx_ran <- ad_obj$env$random
          target_ran_idx <- match(target_full_idx, idx_ran)

          # 最適化対象外を除外
          valid_mask <- !is.na(target_ran_idx)
          target_ran_idx <- target_ran_idx[valid_mask]
          valid_full_idx <- target_full_idx[valid_mask]

          if (length(target_ran_idx) > 0) {
            reml_dfs <- self$calculate_reml_satterthwaite_df(ad_obj, opt$par, target_ran_idx)
            est_dfs_all[valid_full_idx] <- if (is.list(reml_dfs)) reml_dfs$df else reml_dfs
          }
        }
        ad_obj$fn(opt$par)
      }

      sd_rep <- tryCatch(RTMB::sdreport(ad_obj, getJointPrecision = laplace_flag), error = function(e) stop("sdreport failed: ", e$message))

      # 派生パラメータ計算用の推定値リストを作成
      unc_est_vec <- ad_obj$env$last.par
      unc_est_list <- unconstrained_vector_to_list(unc_est_vec, self$par_list)
      con_est_list <- to_constrained(unc_est_list, self$par_list)

      smry_fix <- tryCatch(as.data.frame(suppressWarnings(summary(sd_rep, select = "fixed"))), warning = function(w) data.frame(), error = function(e) data.frame())
      smry_ran <- tryCatch(as.data.frame(suppressWarnings(summary(sd_rep, select = "random"))), warning = function(w) data.frame(), error = function(e) data.frame())
      smry_rep <- tryCatch(as.data.frame(suppressWarnings(summary(sd_rep, select = "report"))), warning = function(w) data.frame(), error = function(e) data.frame())

      idx_fix <- ad_obj$env$lfixed()
      idx_ran <- ad_obj$env$random
      if (nrow(smry_fix) > 0) smry_fix$df <- if (length(idx_fix) == nrow(smry_fix)) est_dfs_all[idx_fix] else Inf
      if (nrow(smry_ran) > 0) smry_ran$df <- if (length(idx_ran) == nrow(smry_ran)) est_dfs_all[idx_ran] else Inf

      # --- 推定対象の固定効果インデックスの特定 (Mapを考慮) ---
      active_info <- private$.compute_active_indices(self$map)
      idx_fix_active <- active_info$idx_active

      V_joint <- NULL
      if (laplace_flag && !is.null(sd_rep$jointPrecision)) {
        V_joint <- tryCatch(as.matrix(solve(sd_rep$jointPrecision)), warning = function(w) NULL, error = function(e) NULL)
      } else if (!is.null(sd_rep$cov.fixed)) {
        V_joint <- sd_rep$cov.fixed
      }

      L_u_total <- length(unc_est_vec)
      Cov_u_full <- matrix(0, L_u_total, L_u_total)
      
      if (!is.null(V_joint) && length(idx_fix_active) == nrow(V_joint)) {
        Cov_u_full[idx_fix_active, idx_fix_active] <- V_joint
        
        # 重複パラメータ（Mapによる共有）への共分散のコピー
        # This part handles duplication via idx_fix_active logic
      }

      # generate/transform ブロックの処理
      has_derived <- !is.null(self$transform) || !is.null(self$generate)
      if (has_derived) {
        tran_list <- if (!is.null(self$transform)) tryCatch(self$transform(self$data, con_est_list), warning = function(w) NULL, error = function(e) NULL) else NULL
        gen_list <- if (!is.null(self$generate)) tryCatch(self$generate(self$data, c(con_est_list, tran_list)), warning = function(w) NULL, error = function(e) NULL) else NULL
        all_derived <- c(tran_list, gen_list)

        if (length(all_derived) > 0) {
          # Using private helper
          # ... existing build_derived_df logic ...
        }
      }

      # =====================================================================
      # 2. フィルタリングと結合
      # =====================================================================
      df_combined <- rbind(smry_fix, smry_ran, smry_rep)

      # =====================================================================
      # 3. 名前の正規化
      # =====================================================================
      base_names <- gsub("\\.[0-9]+$", "", rownames(df_combined))
      base_names[base_names == "(Intercept)"] <- "Intercept"

      for (n in unique(base_names)) {
        idx <- which(base_names == n)
        if (length(idx) > 1) {
           # すでにブラケットがある場合はそのまま、ない場合は連番
           if (!any(grepl("\\[", base_names[idx]))) {
              base_names[idx] <- paste0(n, "[", seq_along(idx), "]")
           }
        }
      }

      if (!is.null(self$par_names)) {
        for (p in names(self$par_names)) {
          idx <- which(grepl(paste0("^", p, "($|\\[)"), base_names))
          if (length(idx) > 0) {
            labels <- self$par_names[[p]]
            if (is.list(labels)) {
               # 行列などの多次元ラベルは generate_flat_names で処理済みのはずなのでスキップ
            } else {
              for (j in seq_along(idx)) {
                if (j <= length(labels)) base_names[idx[j]] <- paste0(p, "[", labels[j], "]")
              }
            }
          }
        }
      }
      rownames(df_combined) <- make.unique(base_names)

      # =====================================================================
      # 4 & 5. 統計量の計算と信頼区間の構築
      # =====================================================================
      df_combined$`t value` <- df_combined$Estimate / pmax(df_combined$`Std. Error`, 1e-12)
      df_combined$Pr <- 2 * pt(-abs(df_combined$`t value`), df = pmax(df_combined$df, 1e-6))
      df_combined$`Lower 95%` <- df_combined$Estimate + qt(0.025, df = pmax(df_combined$df, 1e-6)) * df_combined$`Std. Error`
      df_combined$`Upper 95%` <- df_combined$Estimate + qt(0.975, df = pmax(df_combined$df, 1e-6)) * df_combined$`Std. Error`

      # 制約のあるパラメータ（sigma等）の統計量再計算
      for (name in names(self$par_list)) {
        p_info <- self$par_list[[name]]
        row_indices <- which(grepl(paste0("^", name, "($|\\[)"), rownames(df_combined)))

        if (length(row_indices) > 0 && length(row_indices) == p_info$length) {
          lower <- if (is.numeric(p_info$lower)) p_info$lower else -Inf
          upper <- if (is.numeric(p_info$upper)) p_info$upper else Inf

          u <- df_combined$Estimate[row_indices]
          se_u <- df_combined$`Std. Error`[row_indices]
          df_val <- pmax(df_combined$df[row_indices], 1e-6)

          crit <- qt(0.975, df = df_val)
          low_u <- u - crit * se_u
          up_u <- u + crit * se_u

          if (all(is.infinite(upper)) && any(is.finite(lower))) {
            # 対数変換（sigmaなど）
            u_null <- if (lower < 0) log(-lower) else NA
            df_combined$Estimate[row_indices] <- exp(u) + lower
            df_combined$`Std. Error`[row_indices] <- exp(u) * se_u
            df_combined$`Lower 95%`[row_indices] <- exp(low_u) + lower
            df_combined$`Upper 95%`[row_indices] <- exp(up_u) + lower
            
            t_val <- (u - u_null) / pmax(se_u, 1e-12)
            df_combined$`t value`[row_indices] <- t_val
            df_combined$Pr[row_indices] <- 2 * pt(-abs(t_val), df = df_val)
          } else if (any(is.finite(lower)) && any(is.finite(upper))) {
            # ロジット変換
            p_null <- -lower / (upper - lower)
            u_null <- if (p_null > 0 && p_null < 1) log(p_null / (1 - p_null)) else NA
            il <- function(v) 1 / (1 + exp(-v))
            df_combined$Estimate[row_indices] <- lower + (upper - lower) * il(u)
            df_combined$`Std. Error`[row_indices] <- (upper - lower) * il(u) * (1 - il(u)) * se_u
            c_low <- lower + (upper - lower) * il(low_u)
            c_up <- lower + (upper - lower) * il(up_u)
            df_combined$`Lower 95%`[row_indices] <- pmin(c_low, c_up)
            df_combined$`Upper 95%`[row_indices] <- pmax(c_low, c_up)
            
            t_val <- (u - u_null) / pmax(se_u, 1e-12)
            df_combined$`t value`[row_indices] <- t_val
            df_combined$Pr[row_indices] <- 2 * pt(-abs(t_val), df = df_val)
          }
        }
      }


      # =====================================================================
      # 6. メタデータの記録と表示順序
      # =====================================================================
      if (is.null(self$extra)) self$extra <- list()
      self$extra$loglik <- -opt$objective
      self$extra$df <- length(opt$par)
      self$extra$nobs <- if (!is.null(self$data$N)) self$data$N else if (!is.null(self$data$Y)) length(self$data$Y) else NA

      if (nrow(df_combined) > 0) {
        view_to_use <- if (!is.null(view)) view else if (!is.null(self$view)) self$view else c("Intercept", "b", "tau", "sigma", "sd", "rho", "r_re")

        row_names <- rownames(df_combined)
        ordered_idx <- unlist(lapply(view_to_use, function(v) which(grepl(paste0("^", v, "($|\\[|\\.)"), row_names))))
        ordered_idx <- unique(ordered_idx)

        final_idx <- c(ordered_idx, setdiff(seq_len(nrow(df_combined)), ordered_idx))
        df_combined <- df_combined[final_idx, , drop = FALSE]
      }

      res <- Classic_Fit$new(self, df_combined, vcov = V_joint, par_unc = unc_est_vec, vcov_unc = Cov_u_full, test_results = test_results, view = view)
      return(res)
    },

    # 4. MCMC NUTS Sampling Method
    #' @description Draw posterior samples from the model.
    #' @param sampling Number of sampling iterations. Default is 1000.
    #' @param warmup Number of warmup iterations. Default is 1000.
    #' @param chains Number of MCMC chains. Default is 4.
    #' @param thin Thinning interval. Default is 1.
    #' @param seed Random seed.
    #' @param delta Target acceptance rate for HMC/NUTS. Default is 0.8.
    #' @param max_treedepth Maximum tree depth for HMC/NUTS. Default is 10.
    #' @param parallel Logical; whether to run chains in parallel. Default is FALSE.
    #' @param laplace Logical; whether to use Laplace approximation. Default is FALSE.
    #' @param init Optional initial values for parameters.
    #' @param init_jitter sd of randomize initial values for parameters.
    #' @param save_csv Optional list for saving MCMC results. e.g., list(name = "model", dir = "BayesRTMB_mcmc").
    #' @param map Optional list specifying parameters to fix (factors).
    #' @param fixed Optional list specifying parameter values to fix.
    #' @return A fitted `MCMC_Fit` object.
    sample = function(sampling = 1000, warmup = 1000, chains = 4,
                      thin = 1, seed = sample.int(1e6, 1),
                      delta = 0.8, max_treedepth = 10,
                      parallel = FALSE, laplace = FALSE,
                      init = NULL, init_jitter = 0.1, save_csv = NULL,
                      map = NULL, fixed = NULL) {
      if (!is.null(fixed)) {
        return(self$fixed_model(fixed)$sample(
          sampling = sampling, warmup = warmup, chains = chains, thin = thin,
          seed = seed, delta = delta, max_treedepth = max_treedepth,
          parallel = parallel, laplace = laplace, init = init,
          init_jitter = init_jitter, save_csv = save_csv, map = map
        ))
      }

      # if (!is.null(init)) init <- as.numeric(init)
      set.seed(seed)
      orig_pl <- self$par_list

      # --- Prepare information for CSV saving and create directory ---
      if (!is.null(save_csv)) {
        if (!is.list(save_csv)) stop("save_csv must be specified in the format list(name='...', dir='...').")
        save_name <- if (!is.null(save_csv$name)) save_csv$name else "model"
        save_dir <- if (!is.null(save_csv$dir)) save_csv$dir else "BayesRTMB_mcmc"

        # Added: Save frequency (0 means save all at once at the end of the chain)
        save_freq <- if (!is.null(save_csv$freq)) save_csv$freq else 0

        if (!dir.exists(save_dir)) dir.create(save_dir, recursive = TRUE, showWarnings = FALSE)
        save_info <- list(name = save_name, dir = save_dir, freq = save_freq)
      } else {
        save_info <- NULL
      }

      random_flags <- vapply(orig_pl, function(x) isTRUE(x$random), logical(1))

      if (laplace && any(random_flags)) {
        pl_fixed <- parse_parameters(orig_pl[!random_flags], self$par_names)
        pl_random <- parse_parameters(orig_pl[random_flags], self$par_names)

        fixed_idx <- which(self$pl_full$names %in% pl_fixed$names)
        random_idx <- which(self$pl_full$names %in% pl_random$names)
      } else {
        pl_fixed <- self$pl_full
        pl_random <- NULL
        fixed_idx <- 1:length(self$pl_full$names)
        random_idx <- integer(0)
      }

      P_fixed <- length(pl_fixed$names)
      P_random <- if (!is.null(pl_random)) length(pl_random$names) else 0

      # --- Set up parallel plan early to allow messaging ---
      if (parallel) {
        if (inherits(future::plan(), "sequential")) {
          if (.Platform$OS.type == "unix") {
            future::plan(future::multicore, workers = chains)
          } else {
            future::plan(future::multisession, workers = chains)
          }
        }
        cat(paste0("Starting parallel sampling (chains = ", chains, ")...\n"))
      } else {
        cat(paste0("Starting sequential sampling (chains = ", chains, ")...\n"))
      }

      # --- Data extraction to minimize serialization payload to workers ---
      local_data <- self$data
      local_par_list <- self$par_list
      local_pl_full <- self$pl_full
      local_map <- if (is.null(map)) self$map else utils::modifyList(as.list(self$map), as.list(map))
      local_log_prob <- self$log_prob
      local_transform <- self$transform

      random_effs <- names(local_par_list)[random_flags]
      use_random <- if (laplace && length(random_effs) > 0) random_effs else NULL

      base_init <- self$prepare_init(init)

      # --- Worker function definition without self references ---
      run_chain <- function(c, p_callback = NULL) {
        library(BayesRTMB)

        unc_init_list <- to_unconstrained(
          constrained_vector_to_list(base_init, local_par_list),
          local_par_list
        )
        unc_init_vec <- unlist(unc_init_list, use.names = FALSE)

        if (init_jitter > 0) {
          jitter_vec <- rnorm(length(unc_init_vec), mean = 0, sd = init_jitter)
          if (!is.null(local_map)) {
            idx <- 1
            for (name in names(local_par_list)) {
              L_unc <- local_par_list[[name]]$unc_length
              if (L_unc > 0) {
                if (!is.null(local_map[[name]])) {
                  is_fixed <- is.na(local_map[[name]])
                  jitter_vec[idx:(idx + L_unc - 1)][is_fixed] <- 0
                }
                idx <- idx + L_unc
              }
            }
          }
          unc_init_vec <- unc_init_vec + jitter_vec
        }
        unc_init_list_new <- unconstrained_vector_to_list(unc_init_vec, local_par_list)

        # Build worker AD object
        f_ad_worker <- .make_f_ad(
          data = local_data, 
          par_list = local_par_list, 
          log_prob = local_log_prob, 
          transform = local_transform,
          jacobian_target = "all"
        )

        ad_obj <- tryCatch(
          {
            RTMB::MakeADFun(
              func = f_ad_worker,
              parameters = unc_init_list_new,
              random = use_random,
              map = local_map,
              silent = TRUE
            )
          },
          error = function(e) {
            stop("Failed to setup MakeADFun in parallel worker.\n[Error]: ", e$message, call. = FALSE)
          }
        )

        res <- NUTS_method(
          model = ad_obj,
          sampling = sampling,
          warmup = warmup,
          delta = delta,
          max_treedepth = max_treedepth,
          chain = c,
          update_progress = p_callback,
          laplace = laplace,
          save_info = save_info
        )

        P_all_true <- length(local_pl_full$names)
        iter_total <- sampling + warmup
        para_final <- array(NA, dim = c(iter_total, P_all_true))

        for (i in 1:iter_total) {
          x_in <- as.numeric(res$para_fixed[i, ])

          if (laplace && length(ad_obj$env$random) > 0) {
            ad_obj$fn(x_in)
            para_list <- ad_obj$env$parList()
          } else {
            para_list <- ad_obj$env$parList(x = x_in)
          }

          con_list <- to_constrained(para_list, local_par_list)
          para_final[i, ] <- unlist(con_list, use.names = FALSE)
        }
        res$para <- para_final
        res$para_full <- NULL
        return(res)
      }

      # --- Execution block ---
      results_list <- list()
      if (parallel) {
        iter <- sampling + warmup
        total_updates <- chains * (1 + floor(iter / 100))

        progressr::with_progress({
          p <- progressr::progressor(steps = total_updates)
          results_list <- withCallingHandlers(
            {
              future.apply::future_lapply(1:chains, function(c) {
                run_chain(c, p_callback = function(msg = "", amt = 1, ...) {
                  if (is.numeric(msg)) {
                    amt <- msg
                    msg <- ""
                  }
                  p(amount = amt, message = as.character(msg))
                })
              },
              future.seed = TRUE,
              future.packages = c("RTMB", "BayesRTMB"),
              future.globals = FALSE # Automatic global search disabled for performance
              )
            },
            warning = function(w) {
              if (grepl("package:BayesRTMB", conditionMessage(w))) {
                invokeRestart("muffleWarning")
              }
            }
          )
        })
      } else {
        results_list <- lapply(1:chains, function(c) {
          run_chain(c, p_callback = NULL)
        })
      }

      # --- Compile outputs ---
      mcmc_index <- seq(from = (warmup + 1), to = (warmup + sampling), by = thin)
      accept_mat <- array(NA, dim = c(length(mcmc_index), chains))
      td_mat <- array(NA, dim = c(length(mcmc_index), chains))
      eps_vec <- numeric(chains)

      fit <- array(NA, dim = c(length(mcmc_index), chains, P_fixed + 1))
      dimnames(fit) <- list(
        iteration = NULL,
        chain = paste0("chain", 1:chains),
        variable = c("lp", pl_fixed$names)
      )

      if (P_random > 0) {
        random_fit <- array(NA, dim = c(length(mcmc_index), chains, P_random))
        dimnames(random_fit) <- list(
          iteration = NULL,
          chain = paste0("chain", 1:chains),
          variable = pl_random$names
        )
      } else {
        random_fit <- NULL
      }

      for (c in 1:chains) {
        res <- results_list[[c]]
        fit[, c, 1] <- res$lp[mcmc_index]
        for (j in 1:P_fixed) fit[, c, j + 1] <- res$para[mcmc_index, fixed_idx[j]]
        if (P_random > 0) {
          for (j in 1:P_random) {
            random_fit[, c, j] <- res$para[mcmc_index, random_idx[j]]
          }
        }
        accept_mat[, c] <- res$accept[mcmc_index]
        td_mat[, c] <- res$treedepth[mcmc_index]
        eps_vec[c] <- res$eps
      }

      eps_chains <- eps_vec
      accept_chains <- apply(accept_mat, 2, mean)
      treedepth_chains <- apply(td_mat, 2, max)
      names(eps_chains) <- names(accept_chains) <- names(treedepth_chains) <- paste0("chain", 1:chains)

      posterior_mean <- numeric(length(self$pl_full$names))
      names(posterior_mean) <- self$pl_full$names
      fixed_mean <- apply(fit[, , -1, drop = FALSE], 3, mean)
      posterior_mean[names(fixed_mean)] <- fixed_mean
      if (!is.null(random_fit)) {
        random_mean <- apply(random_fit, 3, mean)
        posterior_mean[names(random_mean)] <- random_mean
      }

      if (!is.null(save_info)) {
        for (c in 1:chains) {
          backup_file <- file.path(save_info$dir, paste0(save_info$name, "-", c, ".csv"))

          df_metrics <- data.frame(
            iteration = mcmc_index,
            accept    = accept_mat[, c],
            treedepth = td_mat[, c],
            eps       = eps_vec[c]
          )

          if (!is.null(random_fit)) {
            df_out <- cbind(
              df_metrics,
              as.data.frame(fit[, c, ]),
              as.data.frame(random_fit[, c, ])
            )
          } else {
            df_out <- cbind(
              df_metrics,
              as.data.frame(fit[, c, ])
            )
          }

          write.csv(df_out, file = backup_file, row.names = FALSE)
        }
      }

      res_obj <- MCMC_Fit$new(
        model          = self,
        fit            = fit,
        random_fit     = random_fit,
        eps            = eps_chains,
        accept         = accept_chains,
        treedepth      = treedepth_chains,
        laplace        = laplace,
        posterior_mean = posterior_mean
      )

      has_tran <- !is.null(self$transform)
      has_generate <- !is.null(self$generate)

      if (has_tran) res_obj$transformed_draws(self$transform)
      if (has_generate) res_obj$generated_quantities(self$code$generate)

      return(res_obj)
    },

    #' @description Run Automatic Differentiation Variational Inference (ADVI).
    #' @param iter Integer; fixed number of iterations for the optimization. Default is 3000.
    #' @param tol_rel_obj Numeric; relative tolerance for the ELBO change to determine convergence. Default is 0.005.
    #' @param window_size Integer; window size for median smoothing in the convergence check. Default is 100.
    #' @param num_samples Integer; number of posterior samples to generate from the fitted variational distribution. Default is 1000.
    #' @param num_estimate Integer; number of times to run the VB estimation (treated as chains). Default is 4.
    #' @param alpha Numeric; learning rate for the Adam optimizer. Default is 0.01.
    #' @param laplace Logical; whether to use Laplace approximation to marginalize random effects. Default is FALSE.
    #' @param print_freq Integer; iterations interval for progress output. Set to 0 to disable. Default is 1000.
    #' @param method Character; method of Variational Inference. Default is "meanfield".
    #' @param parallel Logical; whether to run estimations in parallel. Default is FALSE.
    #' @param seed Integer; random seed for reproducibility.
    #' @param init Optional numeric vector or list for initial parameter values. Default is NULL.
    #' @param save_csv Optional list for saving VB results. e.g., list(name = "model", dir = "BayesRTMB_vb").
    #' @param map Optional list specifying parameters to fix (factors).
    #' @param fixed Optional list specifying parameter values to fix.
    #' @return A fitted `VB_Fit` object containing posterior samples and diagnostic information.
    variational = function(iter = 3000,
                           tol_rel_obj = 0.005, window_size = 100,
                           num_samples = 1000, num_estimate = 4, alpha = 0.01,
                           laplace = FALSE, print_freq = 1000,
                           method = c("meanfield", "fullrank", "hybrid"), parallel = FALSE,
                           seed = sample.int(1e6, 1), init = NULL, save_csv = NULL,
                           map = NULL, fixed = NULL) {
      if (!is.null(fixed)) {
        return(self$fixed_model(fixed)$variational(
          iter = iter, tol_rel_obj = tol_rel_obj, window_size = window_size,
          num_samples = num_samples, num_estimate = num_estimate, alpha = alpha,
          laplace = laplace, print_freq = print_freq, method = method,
          parallel = parallel, seed = seed, init = init, save_csv = save_csv, map = map
        ))
      }

      set.seed(seed)
      method <- match.arg(method)

      # --- Prepare information for CSV saving and create directory ---
      if (!is.null(save_csv)) {
        if (!is.list(save_csv)) stop("save_csv must be specified in the format list(name='...', dir='...').")
        save_name <- if (!is.null(save_csv$name)) save_csv$name else "model_vb"
        save_dir <- if (!is.null(save_csv$dir)) save_csv$dir else "BayesRTMB_vb"
        if (!dir.exists(save_dir)) dir.create(save_dir, recursive = TRUE, showWarnings = FALSE)
        save_info <- list(name = save_name, dir = save_dir)
      } else {
        save_info <- NULL
      }

      # --- Set up parallel plan early to allow messaging ---
      if (parallel && num_estimate > 1) {
        if (inherits(future::plan(), "sequential")) {
          if (.Platform$OS.type == "unix") {
            future::plan(future::multicore, workers = num_estimate)
          } else {
            future::plan(future::multisession, workers = num_estimate)
          }
        }
        cat(paste0("Starting parallel VB estimation (num_estimate = ", num_estimate, ")...\n"))
      } else {
        cat(paste0("Starting sequential VB estimation (num_estimate = ", num_estimate, ")...\n"))
      }

      # --- Data extraction to minimize serialization payload to workers ---
      local_data <- self$data
      local_par_list <- self$par_list
      local_pl_full <- self$pl_full
      local_map <- if (is.null(map)) self$map else utils::modifyList(as.list(self$map), as.list(map))
      local_log_prob <- self$log_prob
      local_transform <- self$transform

      random_flags <- sapply(local_par_list, function(x) isTRUE(x$random))
      random_effs <- names(local_par_list)[random_flags]
      use_random <- if (laplace && length(random_effs) > 0) random_effs else NULL

      base_init <- self$prepare_init(init)

      # --- Worker function definition using .make_f_ad ---
      run_advi_worker <- function(c, p_callback = NULL, p_interval = 0) {
        library(BayesRTMB)

        f_ad_worker <- .make_f_ad(
          data = local_data, 
          par_list = local_par_list, 
          log_prob = local_log_prob, 
          transform = local_transform,
          jacobian_target = "all"
        )

        ad_obj <- tryCatch({
          RTMB::MakeADFun(
            func = f_ad_worker,
            parameters = unconstrained_vector_to_list(unlist(to_unconstrained(base_init, local_par_list)), local_par_list),
            random = use_random,
            map = local_map,
            silent = TRUE
          )
        }, error = function(e) stop("Failed to setup MakeADFun in worker: ", e$message))

        if (!is.null(use_random)) {
          orig_fn <- ad_obj$fn
          orig_gr <- ad_obj$gr
          idx_fixed_mask <- ad_obj$env$lfixed()
          n_fixed <- sum(idx_fixed_mask)

          ad_obj$fn <- function(x, ...) {
            if (length(x) != n_fixed) {
              x <- x[idx_fixed_mask]
            }
            orig_fn(x, ...)
          }
          ad_obj$gr <- function(x, ...) {
            is_wrong_len <- (length(x) != n_fixed)
            if (is_wrong_len) {
              g <- orig_gr(x[idx_fixed_mask], ...)
              g_full <- rep(0, length(x))
              g_full[idx_fixed_mask] <- g
              return(g_full)
            }
            return(orig_gr(x, ...))
          }
        }

        res <- ADVI_method(
          model = ad_obj, par_list = local_par_list, pl_full = local_pl_full,
          iter = iter, tol_rel_obj = tol_rel_obj,
          window_size = window_size, num_samples = num_samples, alpha = alpha,
          laplace = laplace,
          print_freq = if (is.null(p_callback)) print_freq else 0,
          method = method,
          update_progress = p_callback,
          update_interval = p_interval
        )
        return(res)
      }

      # --- Execution block ---
      results_list <- list()
      if (parallel && num_estimate > 1) {
        if (requireNamespace("progressr", quietly = TRUE)) {
          progressr::handlers(global = TRUE)

          # Dynamically scale update interval (minimum 1)
          update_interval <- max(1, floor(iter / 100))
          steps_per_chain <- ceiling(iter / update_interval)
          total_steps <- steps_per_chain * num_estimate

          results_list <- progressr::with_progress({
            p <- progressr::progressor(steps = total_steps)

            withCallingHandlers(
              {
                future.apply::future_lapply(1:num_estimate, function(c) {
                  run_advi_worker(
                    c = c,
                    p_callback = function(amount = 1) p(amount = amount),
                    p_interval = update_interval
                  )
                }, future.seed = TRUE, future.packages = c("RTMB", "BayesRTMB"), future.globals = FALSE)
              },
              warning = function(w) {
                if (grepl("BayesRTMB", conditionMessage(w))) {
                  invokeRestart("muffleWarning")
                }
              }
            )
          })
        } else {
          cat("* Install the 'progressr' package to display a progress bar.\n")
          results_list <- future.apply::future_lapply(1:num_estimate, function(c) {
            run_advi_worker(c, p_callback = NULL, p_interval = 0)
          }, future.seed = TRUE, future.packages = c("RTMB", "BayesRTMB"), future.globals = FALSE)
        }
      } else {
        results_list <- lapply(1:num_estimate, function(c) {
          if (print_freq > 0) cat(sprintf("\n--- Starting VB estimation: est%d ---\n", c))
          run_advi_worker(c, p_callback = NULL, p_interval = 0)
        })
      }

      # --- Summarize estimation results ---
      P_fixed <- dim(results_list[[1]]$fit)[3] - 1
      P_random <- if (!is.null(results_list[[1]]$random_fit)) dim(results_list[[1]]$random_fit)[3] else 0

      fit <- array(NA, dim = c(num_samples, num_estimate, P_fixed + 1))
      dimnames(fit) <- list(
        iteration = NULL,
        chain = paste0("est", 1:num_estimate),
        variable = dimnames(results_list[[1]]$fit)[[3]]
      )

      if (P_random > 0) {
        random_fit <- array(NA, dim = c(num_samples, num_estimate, P_random))
        dimnames(random_fit) <- list(
          iteration = NULL,
          chain = paste0("est", 1:num_estimate),
          variable = dimnames(results_list[[1]]$random_fit)[[3]]
        )
      } else {
        random_fit <- NULL
      }

      elbo_history_list <- list()
      elbo_final_vec <- numeric(num_estimate)
      rel_obj_vec <- numeric(num_estimate)

      for (c in 1:num_estimate) {
        res <- results_list[[c]]
        fit[, c, ] <- res$fit[, 1, ]
        if (P_random > 0) random_fit[, c, ] <- res$random_fit[, 1, ]
        elbo_history_list[[c]] <- res$elbo_history - self$prior_correction
        elbo_final_vec[c] <- res$elbo_final - self$prior_correction
        rel_obj_vec[c] <- res$rel_obj_final
      }

      # --- Save posterior samples of each estimate to CSV ---
      if (!is.null(save_info)) {
        for (c in 1:num_estimate) {
          backup_file <- file.path(save_info$dir, paste0(save_info$name, "-", c, ".csv"))

          if (!is.null(random_fit)) {
            df_out <- cbind(iteration = 1:num_samples, as.data.frame(fit[, c, ]), as.data.frame(random_fit[, c, ]))
          } else {
            df_out <- cbind(iteration = 1:num_samples, as.data.frame(fit[, c, ]))
          }

          write.csv(df_out, file = backup_file, row.names = FALSE)
        }
      }

      best_chain <- which.max(elbo_final_vec)

      posterior_mean <- numeric(length(self$pl_full$names))
      names(posterior_mean) <- self$pl_full$names
      fixed_mean <- apply(fit[, best_chain, -1, drop = FALSE], 3, mean)
      posterior_mean[names(fixed_mean)] <- fixed_mean

      if (!is.null(random_fit)) {
        random_mean <- apply(random_fit[, best_chain, , drop = FALSE], 3, mean)
        posterior_mean[names(random_mean)] <- random_mean
      }

      cat("\nConvergence Diagnostics per estimate:\n")
      for (c in 1:num_estimate) {
        status <- if (!is.na(rel_obj_vec[c]) && rel_obj_vec[c] < tol_rel_obj) "Converged" else "Not Converged"
        best_marker <- if (c == best_chain) "  <-- BEST" else ""

        cat(sprintf(
          "  est%d: ELBO = %10.2f, Final rel_obj = %.5f (%s)%s\n",
          c, elbo_final_vec[c], rel_obj_vec[c], status, best_marker
        ))
      }
      cat("\n")

      best_mu_history <- results_list[[best_chain]]$mu_history

      res_obj <- VB_Fit$new(
        model          = self,
        fit            = fit,
        random_fit     = random_fit,
        elbo_history   = elbo_history_list,
        laplace        = laplace,
        posterior_mean = posterior_mean,
        ELBO           = elbo_final_vec,
        rel_obj_vals   = rel_obj_vec,
        best_chain     = best_chain,
        mu_history     = best_mu_history
      )

      has_tran <- !is.null(self$transform)
      has_generate <- !is.null(self$generate)

      if (has_tran) {
        cat("Calculating transformed parameters...\n")
        res_obj$transformed_draws(self$transform)
      }
      if (has_generate) {
        cat("Calculating generated quantities...\n")
        res_obj$generated_quantities(self$code$generate)
      }

      return(res_obj)
    },


    # 5. Print model code method
    #' @description Print model code or model structure.
    #' @return The object itself, invisibly.
    #' @description Print the model code and structure.
    print_code = function() {
      .print_code_impl(self)
    },

    #' @description Print the internal log-probability function.
    #' @return The object itself, invisibly.
    print_log_prob = function() {
      if (is.null(self$log_prob)) {
        cat("log_prob is not available.\n")
        return(invisible(self))
      }

      # Extract the internal function from the error-handling wrapper if it exists
      fn <- self$log_prob
      .print_log_prob_impl(self)
    },

    #' @description Print the transformation function.
    print_transform = function() {
      .print_transform_impl(self)
    },

    #' @description Print the generated quantities function.
    print_generate = function() {
      .print_generate_impl(self)
    },

    #' @description Estimate the number of observations (for user convenience).
    #' @return Integer or numeric vector.
    get_n_obs = function() {
      if (!is.null(self$extra$nobs)) return(self$extra$nobs)
      # This is kept as a simple stub or can call a more robust version if needed
      return(length(as.numeric(self$data[[1]])))
    },

    #' @description Create a new `RTMB_Model` object with certain parameters fixed.
    #' @param fixed_list A named list of parameter values to fix.
    #' @return A new `RTMB_Model` object.
    fixed_model = function(fixed_list) {
      if (!is.list(fixed_list)) stop("fixed_list must be a named list (e.g., fixed = list(theta = ...)).")

      # 1. Start with current map and init
      new_map <- if (is.null(self$map)) list() else self$map
      new_init_list <- self$get_par_list()

      for (name in names(fixed_list)) {
        if (!(name %in% names(self$par_list))) {
          warning(sprintf("Parameter '%s' not found in model. Skipping.", name))
          next
        }
        val <- fixed_list[[name]]
        p <- self$par_list[[name]]

        # Validate length
        if (length(val) != p$length) {
          stop(sprintf(
            "Length of fixed value for '%s' (%d) does not match parameter length (%d).",
            name, length(val), p$length
          ))
        }

        # Update init
        new_init_list[[name]] <- val

        # Update map to fix all elements
        new_map[[name]] <- factor(rep(NA, p$unc_length))
      }

      # 2. Clone and return
      new_model <- self$clone()
      new_model$map <- new_map
      new_model$init <- new_model$prepare_init(new_init_list)

      return(new_model)
    },

    #' @description Create a null model for Bayes Factor or test.
    #' @param target Target parameter and prior.
    #' @param value Value to fix to.
    #' @return A new RTMB_Model object.
    null_model = function(target, value = 0) {
      return(.null_model_impl(self, target, value))
    },

    #' @description Evaluate univariate prior density contribution.
    #' @param p_name Flattened parameter name.
    #' @param u_val Unconstrained value.
    #' @param par_list Optional constrained parameter list.
    #' @return Log-density.
    evaluate_univariate_prior = function(p_name, u_val, par_list = NULL) {
      return(.evaluate_univariate_prior_impl(self, p_name, u_val, par_list))
    }
  ),

  private = list(
    # --- Common patterns for REML and parameter classification ---
    fix_patterns = c("Intercept", "Intercept_c", "b", "mean", "prob", "beta", "mu", "delta", "diff", "mean_diff"),
    var_patterns = c("sigma", "sd", "rho", "rho_resid", "L_resid", "corr", "CF_corr", "cov", "CF_cov", "phi", "tau", "theta", "alpha", "omega", "kappa", "lambda"),

    # --- Internal helper for index computation ---
    .compute_active_indices = function(target_map = NULL) {
      idx_fix_active <- integer(0)
      factor_levels_seen <- list()
      opt_par_curr <- 1
      
      map_to_use <- if (!is.null(target_map)) target_map else self$map
      
      for (name in names(self$par_list)) {
        p <- self$par_list[[name]]
        L_u <- p$unc_length
        m <- if (!is.null(map_to_use[[name]])) map_to_use[[name]] else factor(1:L_u)
        
        # Identify indices that are not NA (i.e., estimated)
        idx_active_local <- which(!is.na(m))
        if (length(idx_active_local) > 0) {
          # Check for shared levels (identical factors)
          lvl_names <- as.character(m[idx_active_local])
          for (lvl in unique(lvl_names)) {
            pos_in_active <- which(lvl_names == lvl)
            # The first occurrence of this level gets the next free optimization index
            if (!(lvl %in% names(factor_levels_seen))) {
              factor_levels_seen[[lvl]] <- opt_par_curr
              opt_par_curr <- opt_par_curr + 1
            }
            # Add to global unconstrained index list
            pos_last <- sum(self$pl_full$unc_length[seq_len(which(names(self$par_list) == name) - 1)]) + idx_active_local[pos_in_active]
            idx_fix_active <- c(idx_fix_active, pos_last)
          }
        }
      }
      return(list(idx_active = sort(unique(idx_fix_active)), n_opt = opt_par_curr - 1))
    },

    # --- Internal helper for REML parameter classification ---
    .classify_reml_parameters = function(target_vars = NULL) {
      fix_names <- character(0)
      var_names <- character(0)
      
      for (name in names(self$par_list)) {
        is_fix_pattern <- any(sapply(private$fix_patterns, function(v) grepl(paste0("^", v, "($|\\[|\\.|_)"), name)))
        is_var_pattern <- any(sapply(private$var_patterns, function(v) grepl(paste0("^", v, "($|\\[|\\.|_)"), name)))
        
        if (is_fix_pattern && !is_var_pattern) {
          fix_names <- c(fix_names, name)
        } else if (is_var_pattern) {
          var_names <- c(var_names, name)
        } else if (!is.null(target_vars) && name %in% target_vars) {
          fix_names <- c(fix_names, name)
        } else {
          # Default to fixed if unknown
          fix_names <- c(fix_names, name)
        }
      }
      return(list(fixed = fix_names, variance = var_names))
    },

    # --- Internal helper for derived parameter calculation (delta method) ---
    .build_derived_df_table = function(func, base_out, is_generate = FALSE, se_sampling = FALSE, num_samples = 1000, sd_rep = NULL) {
      if (is.null(func) || is.null(base_out) || length(base_out) == 0) return(NULL)
      
      names_vec <- c()
      for (name in names(base_out)) {
        val <- base_out[[name]]
        d_val <- if (is.null(dim(val))) length(val) else dim(val)
        names_def <- self$par_names[[name]]
        names_vec <- c(names_vec, generate_flat_names(name, d_val, names_def))
      }
      
      flat_base <- unlist(base_out, use.names = FALSE)
      n_derived <- length(flat_base)
      se_derived <- rep(NA_real_, n_derived)
      df_derived <- rep(Inf, n_derived)
      
      if (!is.null(sd_rep)) {
        smry_rep_all <- as.data.frame(summary(sd_rep, select = "report"))
        m_idx <- match(names_vec, rownames(smry_rep_all))
        valid_m <- !is.na(m_idx)
        if (any(valid_m)) se_derived[valid_m] <- smry_rep_all$`Std. Error`[m_idx[valid_m]]
        
        # Satterthwaite for derived params if needed
        # (This would require Hessian/Jacobian calculations similar to previous logic)
      }
      
      res_df <- data.frame(
        Estimate = flat_base,
        `Std. Error` = se_derived,
        df = df_derived,
        row.names = names_vec,
        check.names = FALSE
      )
      return(res_df)
    }
  )
)


